package com.bornfire.brf.entities;

import java.util.Date;
import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

@Entity
@Table(name = "BRRS_M_PI_SUMMARYTABLE")
public class M_PI_Summary_Entity {

    // Row R8
    private String R8_PRODUCT;
    private String R8_CROSS_REFERENCE;
    private BigDecimal R8_VALUE;
    private BigDecimal R8_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
    private BigDecimal R8_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;

    // Row R9
    private String R9_PRODUCT;
    private String R9_CROSS_REFERENCE;
    private BigDecimal R9_VALUE;
    private BigDecimal R9_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
    private BigDecimal R9_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;

    // Row R10
    private String R10_PRODUCT;
    private String R10_CROSS_REFERENCE;
    private BigDecimal R10_VALUE;
    private BigDecimal R10_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
    private BigDecimal R10_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;

    // Row R11
    private String R11_PRODUCT;
    private String R11_CROSS_REFERENCE;
    private BigDecimal R11_VALUE;
    private BigDecimal R11_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
    private BigDecimal R11_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;

    // Row R12
    private String R12_PRODUCT;
    private String R12_CROSS_REFERENCE;
    private BigDecimal R12_VALUE;
    private BigDecimal R12_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
    private BigDecimal R12_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;

    // Row R13
    private String R13_PRODUCT;
    private String R13_CROSS_REFERENCE;
    private BigDecimal R13_VALUE;
    private BigDecimal R13_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
    private BigDecimal R13_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;

    // Row R14
    private String R14_PRODUCT;
    private String R14_CROSS_REFERENCE;
    private BigDecimal R14_VALUE;
    private BigDecimal R14_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
    private BigDecimal R14_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;

    // Row R15
    private String R15_PRODUCT;
    private String R15_CROSS_REFERENCE;
    private BigDecimal R15_VALUE;
    private BigDecimal R15_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;

    // Row R16
    private String R16_PRODUCT;
    private String R16_CROSS_REFERENCE;
    private BigDecimal R16_VALUE;
    private BigDecimal R16_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;

    // Row R17
    private String R17_PRODUCT;
    private String R17_CROSS_REFERENCE;
    private BigDecimal R17_VALUE;
    private BigDecimal R17_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;

    // Row R18
    private String R18_PRODUCT;
    private String R18_CROSS_REFERENCE;
    private BigDecimal R18_VALUE;
    private BigDecimal R18_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;

    // Row R19
    private String R19_PRODUCT;
    private String R19_CROSS_REFERENCE;
    private BigDecimal R19_VALUE;
    private BigDecimal R19_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;

    // Row R20
    private String R20_PRODUCT;
    private String R20_CROSS_REFERENCE;
    private BigDecimal R20_VALUE;
    private BigDecimal R20_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;

    // Row R21
    private String R21_PRODUCT;
    private String R21_CROSS_REFERENCE;
    private BigDecimal R21_VALUE;
    private BigDecimal R21_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;

    // Row R22
    private String R22_PRODUCT;
    private String R22_CROSS_REFERENCE;
    private BigDecimal R22_VALUE;
    private BigDecimal R22_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;

    // Row R23
    private String R23_PRODUCT;
    private String R23_CROSS_REFERENCE;
    private BigDecimal R23_VALUE;
    private BigDecimal R23_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;

    // Row R24
    private String R24_PRODUCT;
    private String R24_CROSS_REFERENCE;
    private BigDecimal R24_VALUE;
    private BigDecimal R24_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;

    // Row R25
    private String R25_PRODUCT;
    private String R25_CROSS_REFERENCE;
    private BigDecimal R25_VALUE;
    private BigDecimal R25_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;

    // Row R26
    private String R26_PRODUCT;
    private String R26_CROSS_REFERENCE;
    private BigDecimal R26_VALUE;
    private BigDecimal R26_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;

    // Row R27
    private String R27_PRODUCT;
    private String R27_CROSS_REFERENCE;
    private BigDecimal R27_VALUE;
    private BigDecimal R27_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;

    @Id
    @Temporal(TemporalType.DATE)
    @DateTimeFormat(pattern = "dd/MM/yyyy")
    private Date REPORT_DATE;

    private String REPORT_VERSION;
    private String REPORT_FREQUENCY;
    private String REPORT_CODE;
    private String REPORT_DESC;

    private String ENTITY_FLG;
    private String MODIFY_FLG;
    private String DEL_FLG;
	public String getR8_PRODUCT() {
		return R8_PRODUCT;
	}
	public void setR8_PRODUCT(String r8_PRODUCT) {
		R8_PRODUCT = r8_PRODUCT;
	}
	public String getR8_CROSS_REFERENCE() {
		return R8_CROSS_REFERENCE;
	}
	public void setR8_CROSS_REFERENCE(String r8_CROSS_REFERENCE) {
		R8_CROSS_REFERENCE = r8_CROSS_REFERENCE;
	}
	public BigDecimal getR8_VALUE() {
		return R8_VALUE;
	}
	public void setR8_VALUE(BigDecimal r8_VALUE) {
		R8_VALUE = r8_VALUE;
	}
	public BigDecimal getR8_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R8_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR8_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r8_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R8_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r8_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public BigDecimal getR8_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2() {
		return R8_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;
	}
	public void setR8_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2(BigDecimal r8_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2) {
		R8_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2 = r8_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;
	}
	public String getR9_PRODUCT() {
		return R9_PRODUCT;
	}
	public void setR9_PRODUCT(String r9_PRODUCT) {
		R9_PRODUCT = r9_PRODUCT;
	}
	public String getR9_CROSS_REFERENCE() {
		return R9_CROSS_REFERENCE;
	}
	public void setR9_CROSS_REFERENCE(String r9_CROSS_REFERENCE) {
		R9_CROSS_REFERENCE = r9_CROSS_REFERENCE;
	}
	public BigDecimal getR9_VALUE() {
		return R9_VALUE;
	}
	public void setR9_VALUE(BigDecimal r9_VALUE) {
		R9_VALUE = r9_VALUE;
	}
	public BigDecimal getR9_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R9_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR9_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r9_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R9_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r9_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public BigDecimal getR9_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2() {
		return R9_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;
	}
	public void setR9_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2(BigDecimal r9_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2) {
		R9_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2 = r9_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;
	}
	public String getR10_PRODUCT() {
		return R10_PRODUCT;
	}
	public void setR10_PRODUCT(String r10_PRODUCT) {
		R10_PRODUCT = r10_PRODUCT;
	}
	public String getR10_CROSS_REFERENCE() {
		return R10_CROSS_REFERENCE;
	}
	public void setR10_CROSS_REFERENCE(String r10_CROSS_REFERENCE) {
		R10_CROSS_REFERENCE = r10_CROSS_REFERENCE;
	}
	public BigDecimal getR10_VALUE() {
		return R10_VALUE;
	}
	public void setR10_VALUE(BigDecimal r10_VALUE) {
		R10_VALUE = r10_VALUE;
	}
	public BigDecimal getR10_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R10_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR10_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r10_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R10_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r10_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public BigDecimal getR10_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2() {
		return R10_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;
	}
	public void setR10_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2(BigDecimal r10_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2) {
		R10_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2 = r10_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;
	}
	public String getR11_PRODUCT() {
		return R11_PRODUCT;
	}
	public void setR11_PRODUCT(String r11_PRODUCT) {
		R11_PRODUCT = r11_PRODUCT;
	}
	public String getR11_CROSS_REFERENCE() {
		return R11_CROSS_REFERENCE;
	}
	public void setR11_CROSS_REFERENCE(String r11_CROSS_REFERENCE) {
		R11_CROSS_REFERENCE = r11_CROSS_REFERENCE;
	}
	public BigDecimal getR11_VALUE() {
		return R11_VALUE;
	}
	public void setR11_VALUE(BigDecimal r11_VALUE) {
		R11_VALUE = r11_VALUE;
	}
	public BigDecimal getR11_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R11_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR11_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r11_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R11_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r11_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public BigDecimal getR11_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2() {
		return R11_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;
	}
	public void setR11_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2(BigDecimal r11_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2) {
		R11_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2 = r11_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;
	}
	public String getR12_PRODUCT() {
		return R12_PRODUCT;
	}
	public void setR12_PRODUCT(String r12_PRODUCT) {
		R12_PRODUCT = r12_PRODUCT;
	}
	public String getR12_CROSS_REFERENCE() {
		return R12_CROSS_REFERENCE;
	}
	public void setR12_CROSS_REFERENCE(String r12_CROSS_REFERENCE) {
		R12_CROSS_REFERENCE = r12_CROSS_REFERENCE;
	}
	public BigDecimal getR12_VALUE() {
		return R12_VALUE;
	}
	public void setR12_VALUE(BigDecimal r12_VALUE) {
		R12_VALUE = r12_VALUE;
	}
	public BigDecimal getR12_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R12_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR12_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r12_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R12_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r12_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public BigDecimal getR12_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2() {
		return R12_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;
	}
	public void setR12_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2(BigDecimal r12_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2) {
		R12_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2 = r12_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;
	}
	public String getR13_PRODUCT() {
		return R13_PRODUCT;
	}
	public void setR13_PRODUCT(String r13_PRODUCT) {
		R13_PRODUCT = r13_PRODUCT;
	}
	public String getR13_CROSS_REFERENCE() {
		return R13_CROSS_REFERENCE;
	}
	public void setR13_CROSS_REFERENCE(String r13_CROSS_REFERENCE) {
		R13_CROSS_REFERENCE = r13_CROSS_REFERENCE;
	}
	public BigDecimal getR13_VALUE() {
		return R13_VALUE;
	}
	public void setR13_VALUE(BigDecimal r13_VALUE) {
		R13_VALUE = r13_VALUE;
	}
	public BigDecimal getR13_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R13_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR13_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r13_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R13_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r13_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public BigDecimal getR13_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2() {
		return R13_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;
	}
	public void setR13_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2(BigDecimal r13_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2) {
		R13_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2 = r13_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;
	}
	public String getR14_PRODUCT() {
		return R14_PRODUCT;
	}
	public void setR14_PRODUCT(String r14_PRODUCT) {
		R14_PRODUCT = r14_PRODUCT;
	}
	public String getR14_CROSS_REFERENCE() {
		return R14_CROSS_REFERENCE;
	}
	public void setR14_CROSS_REFERENCE(String r14_CROSS_REFERENCE) {
		R14_CROSS_REFERENCE = r14_CROSS_REFERENCE;
	}
	public BigDecimal getR14_VALUE() {
		return R14_VALUE;
	}
	public void setR14_VALUE(BigDecimal r14_VALUE) {
		R14_VALUE = r14_VALUE;
	}
	public BigDecimal getR14_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R14_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR14_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r14_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R14_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r14_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public BigDecimal getR14_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2() {
		return R14_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;
	}
	public void setR14_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2(BigDecimal r14_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2) {
		R14_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2 = r14_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS2;
	}
	public String getR15_PRODUCT() {
		return R15_PRODUCT;
	}
	public void setR15_PRODUCT(String r15_PRODUCT) {
		R15_PRODUCT = r15_PRODUCT;
	}
	public String getR15_CROSS_REFERENCE() {
		return R15_CROSS_REFERENCE;
	}
	public void setR15_CROSS_REFERENCE(String r15_CROSS_REFERENCE) {
		R15_CROSS_REFERENCE = r15_CROSS_REFERENCE;
	}
	public BigDecimal getR15_VALUE() {
		return R15_VALUE;
	}
	public void setR15_VALUE(BigDecimal r15_VALUE) {
		R15_VALUE = r15_VALUE;
	}
	public BigDecimal getR15_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R15_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR15_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r15_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R15_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r15_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public String getR16_PRODUCT() {
		return R16_PRODUCT;
	}
	public void setR16_PRODUCT(String r16_PRODUCT) {
		R16_PRODUCT = r16_PRODUCT;
	}
	public String getR16_CROSS_REFERENCE() {
		return R16_CROSS_REFERENCE;
	}
	public void setR16_CROSS_REFERENCE(String r16_CROSS_REFERENCE) {
		R16_CROSS_REFERENCE = r16_CROSS_REFERENCE;
	}
	public BigDecimal getR16_VALUE() {
		return R16_VALUE;
	}
	public void setR16_VALUE(BigDecimal r16_VALUE) {
		R16_VALUE = r16_VALUE;
	}
	public BigDecimal getR16_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R16_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR16_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r16_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R16_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r16_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public String getR17_PRODUCT() {
		return R17_PRODUCT;
	}
	public void setR17_PRODUCT(String r17_PRODUCT) {
		R17_PRODUCT = r17_PRODUCT;
	}
	public String getR17_CROSS_REFERENCE() {
		return R17_CROSS_REFERENCE;
	}
	public void setR17_CROSS_REFERENCE(String r17_CROSS_REFERENCE) {
		R17_CROSS_REFERENCE = r17_CROSS_REFERENCE;
	}
	public BigDecimal getR17_VALUE() {
		return R17_VALUE;
	}
	public void setR17_VALUE(BigDecimal r17_VALUE) {
		R17_VALUE = r17_VALUE;
	}
	public BigDecimal getR17_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R17_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR17_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r17_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R17_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r17_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public String getR18_PRODUCT() {
		return R18_PRODUCT;
	}
	public void setR18_PRODUCT(String r18_PRODUCT) {
		R18_PRODUCT = r18_PRODUCT;
	}
	public String getR18_CROSS_REFERENCE() {
		return R18_CROSS_REFERENCE;
	}
	public void setR18_CROSS_REFERENCE(String r18_CROSS_REFERENCE) {
		R18_CROSS_REFERENCE = r18_CROSS_REFERENCE;
	}
	public BigDecimal getR18_VALUE() {
		return R18_VALUE;
	}
	public void setR18_VALUE(BigDecimal r18_VALUE) {
		R18_VALUE = r18_VALUE;
	}
	public BigDecimal getR18_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R18_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR18_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r18_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R18_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r18_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public String getR19_PRODUCT() {
		return R19_PRODUCT;
	}
	public void setR19_PRODUCT(String r19_PRODUCT) {
		R19_PRODUCT = r19_PRODUCT;
	}
	public String getR19_CROSS_REFERENCE() {
		return R19_CROSS_REFERENCE;
	}
	public void setR19_CROSS_REFERENCE(String r19_CROSS_REFERENCE) {
		R19_CROSS_REFERENCE = r19_CROSS_REFERENCE;
	}
	public BigDecimal getR19_VALUE() {
		return R19_VALUE;
	}
	public void setR19_VALUE(BigDecimal r19_VALUE) {
		R19_VALUE = r19_VALUE;
	}
	public BigDecimal getR19_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R19_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR19_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r19_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R19_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r19_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public String getR20_PRODUCT() {
		return R20_PRODUCT;
	}
	public void setR20_PRODUCT(String r20_PRODUCT) {
		R20_PRODUCT = r20_PRODUCT;
	}
	public String getR20_CROSS_REFERENCE() {
		return R20_CROSS_REFERENCE;
	}
	public void setR20_CROSS_REFERENCE(String r20_CROSS_REFERENCE) {
		R20_CROSS_REFERENCE = r20_CROSS_REFERENCE;
	}
	public BigDecimal getR20_VALUE() {
		return R20_VALUE;
	}
	public void setR20_VALUE(BigDecimal r20_VALUE) {
		R20_VALUE = r20_VALUE;
	}
	public BigDecimal getR20_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R20_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR20_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r20_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R20_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r20_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public String getR21_PRODUCT() {
		return R21_PRODUCT;
	}
	public void setR21_PRODUCT(String r21_PRODUCT) {
		R21_PRODUCT = r21_PRODUCT;
	}
	public String getR21_CROSS_REFERENCE() {
		return R21_CROSS_REFERENCE;
	}
	public void setR21_CROSS_REFERENCE(String r21_CROSS_REFERENCE) {
		R21_CROSS_REFERENCE = r21_CROSS_REFERENCE;
	}
	public BigDecimal getR21_VALUE() {
		return R21_VALUE;
	}
	public void setR21_VALUE(BigDecimal r21_VALUE) {
		R21_VALUE = r21_VALUE;
	}
	public BigDecimal getR21_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R21_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR21_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r21_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R21_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r21_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public String getR22_PRODUCT() {
		return R22_PRODUCT;
	}
	public void setR22_PRODUCT(String r22_PRODUCT) {
		R22_PRODUCT = r22_PRODUCT;
	}
	public String getR22_CROSS_REFERENCE() {
		return R22_CROSS_REFERENCE;
	}
	public void setR22_CROSS_REFERENCE(String r22_CROSS_REFERENCE) {
		R22_CROSS_REFERENCE = r22_CROSS_REFERENCE;
	}
	public BigDecimal getR22_VALUE() {
		return R22_VALUE;
	}
	public void setR22_VALUE(BigDecimal r22_VALUE) {
		R22_VALUE = r22_VALUE;
	}
	public BigDecimal getR22_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R22_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR22_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r22_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R22_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r22_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public String getR23_PRODUCT() {
		return R23_PRODUCT;
	}
	public void setR23_PRODUCT(String r23_PRODUCT) {
		R23_PRODUCT = r23_PRODUCT;
	}
	public String getR23_CROSS_REFERENCE() {
		return R23_CROSS_REFERENCE;
	}
	public void setR23_CROSS_REFERENCE(String r23_CROSS_REFERENCE) {
		R23_CROSS_REFERENCE = r23_CROSS_REFERENCE;
	}
	public BigDecimal getR23_VALUE() {
		return R23_VALUE;
	}
	public void setR23_VALUE(BigDecimal r23_VALUE) {
		R23_VALUE = r23_VALUE;
	}
	public BigDecimal getR23_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R23_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR23_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r23_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R23_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r23_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public String getR24_PRODUCT() {
		return R24_PRODUCT;
	}
	public void setR24_PRODUCT(String r24_PRODUCT) {
		R24_PRODUCT = r24_PRODUCT;
	}
	public String getR24_CROSS_REFERENCE() {
		return R24_CROSS_REFERENCE;
	}
	public void setR24_CROSS_REFERENCE(String r24_CROSS_REFERENCE) {
		R24_CROSS_REFERENCE = r24_CROSS_REFERENCE;
	}
	public BigDecimal getR24_VALUE() {
		return R24_VALUE;
	}
	public void setR24_VALUE(BigDecimal r24_VALUE) {
		R24_VALUE = r24_VALUE;
	}
	public BigDecimal getR24_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R24_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR24_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r24_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R24_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r24_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public String getR25_PRODUCT() {
		return R25_PRODUCT;
	}
	public void setR25_PRODUCT(String r25_PRODUCT) {
		R25_PRODUCT = r25_PRODUCT;
	}
	public String getR25_CROSS_REFERENCE() {
		return R25_CROSS_REFERENCE;
	}
	public void setR25_CROSS_REFERENCE(String r25_CROSS_REFERENCE) {
		R25_CROSS_REFERENCE = r25_CROSS_REFERENCE;
	}
	public BigDecimal getR25_VALUE() {
		return R25_VALUE;
	}
	public void setR25_VALUE(BigDecimal r25_VALUE) {
		R25_VALUE = r25_VALUE;
	}
	public BigDecimal getR25_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R25_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR25_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r25_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R25_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r25_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public String getR26_PRODUCT() {
		return R26_PRODUCT;
	}
	public void setR26_PRODUCT(String r26_PRODUCT) {
		R26_PRODUCT = r26_PRODUCT;
	}
	public String getR26_CROSS_REFERENCE() {
		return R26_CROSS_REFERENCE;
	}
	public void setR26_CROSS_REFERENCE(String r26_CROSS_REFERENCE) {
		R26_CROSS_REFERENCE = r26_CROSS_REFERENCE;
	}
	public BigDecimal getR26_VALUE() {
		return R26_VALUE;
	}
	public void setR26_VALUE(BigDecimal r26_VALUE) {
		R26_VALUE = r26_VALUE;
	}
	public BigDecimal getR26_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R26_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR26_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r26_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R26_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r26_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public String getR27_PRODUCT() {
		return R27_PRODUCT;
	}
	public void setR27_PRODUCT(String r27_PRODUCT) {
		R27_PRODUCT = r27_PRODUCT;
	}
	public String getR27_CROSS_REFERENCE() {
		return R27_CROSS_REFERENCE;
	}
	public void setR27_CROSS_REFERENCE(String r27_CROSS_REFERENCE) {
		R27_CROSS_REFERENCE = r27_CROSS_REFERENCE;
	}
	public BigDecimal getR27_VALUE() {
		return R27_VALUE;
	}
	public void setR27_VALUE(BigDecimal r27_VALUE) {
		R27_VALUE = r27_VALUE;
	}
	public BigDecimal getR27_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS() {
		return R27_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public void setR27_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS(BigDecimal r27_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS) {
		R27_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS = r27_PRUDENTIAL_MINIMUM_AND_LIMIT_BENCHMARKS;
	}
	public Date getREPORT_DATE() {
		return REPORT_DATE;
	}
	public void setREPORT_DATE(Date rEPORT_DATE) {
		REPORT_DATE = rEPORT_DATE;
	}
	public String getREPORT_VERSION() {
		return REPORT_VERSION;
	}
	public void setREPORT_VERSION(String rEPORT_VERSION) {
		REPORT_VERSION = rEPORT_VERSION;
	}
	public String getREPORT_FREQUENCY() {
		return REPORT_FREQUENCY;
	}
	public void setREPORT_FREQUENCY(String rEPORT_FREQUENCY) {
		REPORT_FREQUENCY = rEPORT_FREQUENCY;
	}
	public String getREPORT_CODE() {
		return REPORT_CODE;
	}
	public void setREPORT_CODE(String rEPORT_CODE) {
		REPORT_CODE = rEPORT_CODE;
	}
	public String getREPORT_DESC() {
		return REPORT_DESC;
	}
	public void setREPORT_DESC(String rEPORT_DESC) {
		REPORT_DESC = rEPORT_DESC;
	}
	public String getENTITY_FLG() {
		return ENTITY_FLG;
	}
	public void setENTITY_FLG(String eNTITY_FLG) {
		ENTITY_FLG = eNTITY_FLG;
	}
	public String getMODIFY_FLG() {
		return MODIFY_FLG;
	}
	public void setMODIFY_FLG(String mODIFY_FLG) {
		MODIFY_FLG = mODIFY_FLG;
	}
	public String getDEL_FLG() {
		return DEL_FLG;
	}
	public void setDEL_FLG(String dEL_FLG) {
		DEL_FLG = dEL_FLG;
	}
	public M_PI_Summary_Entity() {
		super();
		// TODO Auto-generated constructor stub
	}
    
	

}