package com.bornfire.brf.entities;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.print.DocFlavor.STRING;

import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;

@Entity
@Table(name = "BRRS_M_SRWA_12C_SUMMARYTABLE")
public class M_SRWA_12C_Archival_Summary_Entity{
    // R11
    @Column(name = "R11_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE", length = 100)
    private String R11_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;

    // R12
    @Column(name = "R12_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE", length = 100)
    private String R12_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;

    @Column(name = "R12_NUMBER_OF_FAILED_TRADES", precision = 24, scale = 3)
    private BigDecimal R12_NUMBER_OF_FAILED_TRADES;

    @Column(name = "R12_POSITIVE_CURRENT_EXPOSURE", precision = 24, scale = 3)
    private BigDecimal R12_POSITIVE_CURRENT_EXPOSURE;

    @Column(name = "R12_RISK_MULTIPLIER", precision = 24, scale = 3)
    private BigDecimal R12_RISK_MULTIPLIER;

    @Column(name = "R12_RWA", precision = 24, scale = 3)
    private BigDecimal R12_RWA;

    // R13
    @Column(name = "R13_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE", length = 100)
    private String R13_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;

    @Column(name = "R13_NUMBER_OF_FAILED_TRADES", precision = 24, scale = 3)
    private BigDecimal R13_NUMBER_OF_FAILED_TRADES;

    @Column(name = "R13_POSITIVE_CURRENT_EXPOSURE", precision = 24, scale = 3)
    private BigDecimal R13_POSITIVE_CURRENT_EXPOSURE;

    @Column(name = "R13_RISK_MULTIPLIER", precision = 24, scale = 3)
    private BigDecimal R13_RISK_MULTIPLIER;

    @Column(name = "R13_RWA", precision = 24, scale = 3)
    private BigDecimal R13_RWA;

    // R14
    @Column(name = "R14_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE", length = 100)
    private String R14_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;

    @Column(name = "R14_NUMBER_OF_FAILED_TRADES", precision = 24, scale = 3)
    private BigDecimal R14_NUMBER_OF_FAILED_TRADES;

    @Column(name = "R14_POSITIVE_CURRENT_EXPOSURE", precision = 24, scale = 3)
    private BigDecimal R14_POSITIVE_CURRENT_EXPOSURE;

    @Column(name = "R14_RISK_MULTIPLIER", precision = 24, scale = 3)
    private BigDecimal R14_RISK_MULTIPLIER;

    @Column(name = "R14_RWA", precision = 24, scale = 3)
    private BigDecimal R14_RWA;

    // R15
    @Column(name = "R15_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE", length = 100)
    private String R15_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;

    @Column(name = "R15_NUMBER_OF_FAILED_TRADES", precision = 24, scale = 3)
    private BigDecimal R15_NUMBER_OF_FAILED_TRADES;

    @Column(name = "R15_POSITIVE_CURRENT_EXPOSURE", precision = 24, scale = 3)
    private BigDecimal R15_POSITIVE_CURRENT_EXPOSURE;

    @Column(name = "R15_RISK_MULTIPLIER", precision = 24, scale = 3)
    private BigDecimal R15_RISK_MULTIPLIER;

    @Column(name = "R15_RWA", precision = 24, scale = 3)
    private BigDecimal R15_RWA;

    // R16
    @Column(name = "R16_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE", length = 100)
    private String R16_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;

    @Column(name = "R16_NUMBER_OF_FAILED_TRADES", precision = 24, scale = 3)
    private BigDecimal R16_NUMBER_OF_FAILED_TRADES;

    @Column(name = "R16_POSITIVE_CURRENT_EXPOSURE", precision = 24, scale = 3)
    private BigDecimal R16_POSITIVE_CURRENT_EXPOSURE;

    
    @Column(name = "R16_RWA", precision = 24, scale = 3)
    private BigDecimal R16_RWA;

    // R19
    @Column(name = "R19_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE", length = 100)
    private String R19_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;

    // R20
    @Column(name = "R20_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE", length = 100)
    private String R20_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;

    @Column(name = "R20_NUMBER_OF_FAILED_TRADES", precision = 24, scale = 3)
    private BigDecimal R20_NUMBER_OF_FAILED_TRADES;

    @Column(name = "R20_POSITIVE_CURRENT_EXPOSURE", precision = 24, scale = 3)
    private BigDecimal R20_POSITIVE_CURRENT_EXPOSURE;

    @Column(name = "R20_RISK_MULTIPLIER", precision = 24, scale = 3)
    private BigDecimal R20_RISK_MULTIPLIER;

    @Column(name = "R20_RWA", precision = 24, scale = 3)
    private BigDecimal R20_RWA;

    // R21
    @Column(name = "R21_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE", length = 100)
    private String R21_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;

    @Column(name = "R21_NUMBER_OF_FAILED_TRADES", precision = 24, scale = 3)
    private BigDecimal R21_NUMBER_OF_FAILED_TRADES;

    @Column(name = "R21_POSITIVE_CURRENT_EXPOSURE", precision = 24, scale = 3)
    private BigDecimal R21_POSITIVE_CURRENT_EXPOSURE;

    @Column(name = "R21_RISK_MULTIPLIER", precision = 24, scale = 3)
    private BigDecimal R21_RISK_MULTIPLIER;

    @Column(name = "R21_RWA", precision = 24, scale = 3)
    private BigDecimal R21_RWA;

    // R22
    @Column(name = "R22_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE", length = 100)
    private String R22_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;

    @Column(name = "R22_NUMBER_OF_FAILED_TRADES", precision = 24, scale = 3)
    private BigDecimal R22_NUMBER_OF_FAILED_TRADES;

    @Column(name = "R22_POSITIVE_CURRENT_EXPOSURE", precision = 24, scale = 3)
    private BigDecimal R22_POSITIVE_CURRENT_EXPOSURE;

    @Column(name = "R22_RISK_MULTIPLIER", precision = 24, scale = 3)
    private BigDecimal R22_RISK_MULTIPLIER;

    @Column(name = "R22_RWA", precision = 24, scale = 3)
    private BigDecimal R22_RWA;

    // R23
    @Column(name = "R23_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE", length = 100)
    private String R23_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;

    @Column(name = "R23_NUMBER_OF_FAILED_TRADES", precision = 24, scale = 3)
    private BigDecimal R23_NUMBER_OF_FAILED_TRADES;

    @Column(name = "R23_POSITIVE_CURRENT_EXPOSURE", precision = 24, scale = 3)
    private BigDecimal R23_POSITIVE_CURRENT_EXPOSURE;

    @Column(name = "R23_RISK_MULTIPLIER", precision = 24, scale = 3)
    private BigDecimal R23_RISK_MULTIPLIER;

    @Column(name = "R23_RWA", precision = 24, scale = 3)
    private BigDecimal R23_RWA;

    // R24
    @Column(name = "R24_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE", length = 100)
    private String R24_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;

    @Column(name = "R24_NUMBER_OF_FAILED_TRADES", precision = 24, scale = 3)
    private BigDecimal R24_NUMBER_OF_FAILED_TRADES;

    @Column(name = "R24_POSITIVE_CURRENT_EXPOSURE", precision = 24, scale = 3)
    private BigDecimal R24_POSITIVE_CURRENT_EXPOSURE;

    @Column(name = "R24_RISK_MULTIPLIER", precision = 24, scale = 3)
    private BigDecimal R24_RISK_MULTIPLIER;

    @Column(name = "R24_RWA", precision = 24, scale = 3)
    private BigDecimal R24_RWA;

    // R25
    @Column(name = "R25_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE", length = 100)
    private String R25_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;

    @Column(name = "R25_NUMBER_OF_FAILED_TRADES", precision = 24, scale = 3)
    private BigDecimal R25_NUMBER_OF_FAILED_TRADES;

    @Column(name = "R25_POSITIVE_CURRENT_EXPOSURE", precision = 24, scale = 3)
    private BigDecimal R25_POSITIVE_CURRENT_EXPOSURE;

    @Column(name = "R25_RISK_MULTIPLIER", precision = 24, scale = 3)
    private BigDecimal R25_RISK_MULTIPLIER;

    @Column(name = "R25_RWA", precision = 24, scale = 3)
    private BigDecimal R25_RWA;

    // R26
    @Column(name = "R26_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE", length = 100)
    private String R26_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;

    @Column(name = "R26_NUMBER_OF_FAILED_TRADES", precision = 24, scale = 3)
    private BigDecimal R26_NUMBER_OF_FAILED_TRADES;

    @Column(name = "R26_POSITIVE_CURRENT_EXPOSURE", precision = 24, scale = 3)
    private BigDecimal R26_POSITIVE_CURRENT_EXPOSURE;

    @Column(name = "R26_RISK_MULTIPLIER", precision = 24, scale = 3)
    private BigDecimal R26_RISK_MULTIPLIER;

    @Column(name = "R26_RWA", precision = 24, scale = 3)
    private BigDecimal R26_RWA;

    // R27
    @Column(name = "R27_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE", length = 100)
    private String R27_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;

    @Column(name = "R27_NUMBER_OF_FAILED_TRADES", precision = 24, scale = 3)
    private BigDecimal R27_NUMBER_OF_FAILED_TRADES;

    @Column(name = "R27_POSITIVE_CURRENT_EXPOSURE", precision = 24, scale = 3)
    private BigDecimal R27_POSITIVE_CURRENT_EXPOSURE;

    @Column(name = "R27_RWA", precision = 24, scale = 3)
    private BigDecimal R27_RWA;

    // R28
    @Column(name = "R28_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE", length = 100)
    private String R28_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;

    @Column(name = "R28_NUMBER_OF_FAILED_TRADES", precision = 24, scale = 3)
    private BigDecimal R28_NUMBER_OF_FAILED_TRADES;

    @Column(name = "R28_POSITIVE_CURRENT_EXPOSURE", precision = 24, scale = 3)
    private BigDecimal R28_POSITIVE_CURRENT_EXPOSURE;

    @Column(name = "R28_RWA", precision = 24, scale = 3)
    private BigDecimal R28_RWA;

    
    @Temporal(TemporalType.DATE)
    @DateTimeFormat(pattern = "dd-MM-yyyy")
    @Id
    @Column(name = "REPORT_DATE", nullable = false)
    private Date REPORT_DATE;

    @Column(name = "REPORT_VERSION", length = 100)
    private String REPORT_VERSION;

    @Column(name = "REPORT_FREQUENCY", length = 100)
    private String REPORT_FREQUENCY;

        @Column(name = "REPORT_CODE", length = 100)
    private String REPORT_CODE;

    @Column(name = "REPORT_DESC", length = 100)
    private String REPORT_DESC;

@Column(name = "ENTITY_FLG", length = 1)
    private String ENTITY_FLG;

    @Column(name = "MODIFY_FLG", length = 1)
    private String MODIFY_FLG;

    @Column(name = "DEL_FLG", length = 1)
    private String DEL_FLG;

    public M_SRWA_12C_Archival_Summary_Entity(String r11_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE,
            String r12_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE, BigDecimal r12_NUMBER_OF_FAILED_TRADES,
            BigDecimal r12_POSITIVE_CURRENT_EXPOSURE, BigDecimal r12_RISK_MULTIPLIER, BigDecimal r12_RWA,
            String r13_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE, BigDecimal r13_NUMBER_OF_FAILED_TRADES,
            BigDecimal r13_POSITIVE_CURRENT_EXPOSURE, BigDecimal r13_RISK_MULTIPLIER, BigDecimal r13_RWA,
            String r14_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE, BigDecimal r14_NUMBER_OF_FAILED_TRADES,
            BigDecimal r14_POSITIVE_CURRENT_EXPOSURE, BigDecimal r14_RISK_MULTIPLIER, BigDecimal r14_RWA,
            String r15_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE, BigDecimal r15_NUMBER_OF_FAILED_TRADES,
            BigDecimal r15_POSITIVE_CURRENT_EXPOSURE, BigDecimal r15_RISK_MULTIPLIER, BigDecimal r15_RWA,
            String r16_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE, BigDecimal r16_NUMBER_OF_FAILED_TRADES,
            BigDecimal r16_POSITIVE_CURRENT_EXPOSURE, BigDecimal r16_RWA,
            String r19_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE,
            String r20_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE, BigDecimal r20_NUMBER_OF_FAILED_TRADES,
            BigDecimal r20_POSITIVE_CURRENT_EXPOSURE, BigDecimal r20_RISK_MULTIPLIER, BigDecimal r20_RWA,
            String r21_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE, BigDecimal r21_NUMBER_OF_FAILED_TRADES,
            BigDecimal r21_POSITIVE_CURRENT_EXPOSURE, BigDecimal r21_RISK_MULTIPLIER, BigDecimal r21_RWA,
            String r22_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE, BigDecimal r22_NUMBER_OF_FAILED_TRADES,
            BigDecimal r22_POSITIVE_CURRENT_EXPOSURE, BigDecimal r22_RISK_MULTIPLIER, BigDecimal r22_RWA,
            String r23_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE, BigDecimal r23_NUMBER_OF_FAILED_TRADES,
            BigDecimal r23_POSITIVE_CURRENT_EXPOSURE, BigDecimal r23_RISK_MULTIPLIER, BigDecimal r23_RWA,
            String r24_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE, BigDecimal r24_NUMBER_OF_FAILED_TRADES,
            BigDecimal r24_POSITIVE_CURRENT_EXPOSURE, BigDecimal r24_RISK_MULTIPLIER, BigDecimal r24_RWA,
            String r25_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE, BigDecimal r25_NUMBER_OF_FAILED_TRADES,
            BigDecimal r25_POSITIVE_CURRENT_EXPOSURE, BigDecimal r25_RISK_MULTIPLIER, BigDecimal r25_RWA,
            String r26_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE, BigDecimal r26_NUMBER_OF_FAILED_TRADES,
            BigDecimal r26_POSITIVE_CURRENT_EXPOSURE, BigDecimal r26_RISK_MULTIPLIER, BigDecimal r26_RWA,
            String r27_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE, BigDecimal r27_NUMBER_OF_FAILED_TRADES,
            BigDecimal r27_POSITIVE_CURRENT_EXPOSURE, BigDecimal r27_RWA,
            String r28_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE, BigDecimal r28_NUMBER_OF_FAILED_TRADES,
            BigDecimal r28_POSITIVE_CURRENT_EXPOSURE, BigDecimal r28_RWA, Date rEPORT_DATE, String rEPORT_VERSION,
            String rEPORT_FREQUENCY, String rEPORT_CODE, String rEPORT_DESC, String eNTITY_FLG, String mODIFY_FLG,
            String dEL_FLG) {
        R11_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r11_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
        R12_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r12_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
        R12_NUMBER_OF_FAILED_TRADES = r12_NUMBER_OF_FAILED_TRADES;
        R12_POSITIVE_CURRENT_EXPOSURE = r12_POSITIVE_CURRENT_EXPOSURE;
        R12_RISK_MULTIPLIER = r12_RISK_MULTIPLIER;
        R12_RWA = r12_RWA;
        R13_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r13_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
        R13_NUMBER_OF_FAILED_TRADES = r13_NUMBER_OF_FAILED_TRADES;
        R13_POSITIVE_CURRENT_EXPOSURE = r13_POSITIVE_CURRENT_EXPOSURE;
        R13_RISK_MULTIPLIER = r13_RISK_MULTIPLIER;
        R13_RWA = r13_RWA;
        R14_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r14_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
        R14_NUMBER_OF_FAILED_TRADES = r14_NUMBER_OF_FAILED_TRADES;
        R14_POSITIVE_CURRENT_EXPOSURE = r14_POSITIVE_CURRENT_EXPOSURE;
        R14_RISK_MULTIPLIER = r14_RISK_MULTIPLIER;
        R14_RWA = r14_RWA;
        R15_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r15_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
        R15_NUMBER_OF_FAILED_TRADES = r15_NUMBER_OF_FAILED_TRADES;
        R15_POSITIVE_CURRENT_EXPOSURE = r15_POSITIVE_CURRENT_EXPOSURE;
        R15_RISK_MULTIPLIER = r15_RISK_MULTIPLIER;
        R15_RWA = r15_RWA;
        R16_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r16_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
        R16_NUMBER_OF_FAILED_TRADES = r16_NUMBER_OF_FAILED_TRADES;
        R16_POSITIVE_CURRENT_EXPOSURE = r16_POSITIVE_CURRENT_EXPOSURE;
        R16_RWA = r16_RWA;
        R19_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r19_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
        R20_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r20_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
        R20_NUMBER_OF_FAILED_TRADES = r20_NUMBER_OF_FAILED_TRADES;
        R20_POSITIVE_CURRENT_EXPOSURE = r20_POSITIVE_CURRENT_EXPOSURE;
        R20_RISK_MULTIPLIER = r20_RISK_MULTIPLIER;
        R20_RWA = r20_RWA;
        R21_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r21_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
        R21_NUMBER_OF_FAILED_TRADES = r21_NUMBER_OF_FAILED_TRADES;
        R21_POSITIVE_CURRENT_EXPOSURE = r21_POSITIVE_CURRENT_EXPOSURE;
        R21_RISK_MULTIPLIER = r21_RISK_MULTIPLIER;
        R21_RWA = r21_RWA;
        R22_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r22_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
        R22_NUMBER_OF_FAILED_TRADES = r22_NUMBER_OF_FAILED_TRADES;
        R22_POSITIVE_CURRENT_EXPOSURE = r22_POSITIVE_CURRENT_EXPOSURE;
        R22_RISK_MULTIPLIER = r22_RISK_MULTIPLIER;
        R22_RWA = r22_RWA;
        R23_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r23_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
        R23_NUMBER_OF_FAILED_TRADES = r23_NUMBER_OF_FAILED_TRADES;
        R23_POSITIVE_CURRENT_EXPOSURE = r23_POSITIVE_CURRENT_EXPOSURE;
        R23_RISK_MULTIPLIER = r23_RISK_MULTIPLIER;
        R23_RWA = r23_RWA;
        R24_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r24_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
        R24_NUMBER_OF_FAILED_TRADES = r24_NUMBER_OF_FAILED_TRADES;
        R24_POSITIVE_CURRENT_EXPOSURE = r24_POSITIVE_CURRENT_EXPOSURE;
        R24_RISK_MULTIPLIER = r24_RISK_MULTIPLIER;
        R24_RWA = r24_RWA;
        R25_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r25_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
        R25_NUMBER_OF_FAILED_TRADES = r25_NUMBER_OF_FAILED_TRADES;
        R25_POSITIVE_CURRENT_EXPOSURE = r25_POSITIVE_CURRENT_EXPOSURE;
        R25_RISK_MULTIPLIER = r25_RISK_MULTIPLIER;
        R25_RWA = r25_RWA;
        R26_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r26_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
        R26_NUMBER_OF_FAILED_TRADES = r26_NUMBER_OF_FAILED_TRADES;
        R26_POSITIVE_CURRENT_EXPOSURE = r26_POSITIVE_CURRENT_EXPOSURE;
        R26_RISK_MULTIPLIER = r26_RISK_MULTIPLIER;
        R26_RWA = r26_RWA;
        R27_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r27_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
        R27_NUMBER_OF_FAILED_TRADES = r27_NUMBER_OF_FAILED_TRADES;
        R27_POSITIVE_CURRENT_EXPOSURE = r27_POSITIVE_CURRENT_EXPOSURE;
        R27_RWA = r27_RWA;
        R28_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r28_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
        R28_NUMBER_OF_FAILED_TRADES = r28_NUMBER_OF_FAILED_TRADES;
        R28_POSITIVE_CURRENT_EXPOSURE = r28_POSITIVE_CURRENT_EXPOSURE;
        R28_RWA = r28_RWA;
        REPORT_DATE = rEPORT_DATE;
        REPORT_VERSION = rEPORT_VERSION;
        REPORT_FREQUENCY = rEPORT_FREQUENCY;
        REPORT_CODE = rEPORT_CODE;
        REPORT_DESC = rEPORT_DESC;
        ENTITY_FLG = eNTITY_FLG;
        MODIFY_FLG = mODIFY_FLG;
        DEL_FLG = dEL_FLG;
    }

    public String getR11_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE() {
        return R11_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public void setR11_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE(
            String r11_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE) {
        R11_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r11_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public String getR12_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE() {
        return R12_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public void setR12_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE(
            String r12_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE) {
        R12_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r12_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public BigDecimal getR12_NUMBER_OF_FAILED_TRADES() {
        return R12_NUMBER_OF_FAILED_TRADES;
    }

    public void setR12_NUMBER_OF_FAILED_TRADES(BigDecimal r12_NUMBER_OF_FAILED_TRADES) {
        R12_NUMBER_OF_FAILED_TRADES = r12_NUMBER_OF_FAILED_TRADES;
    }

    public BigDecimal getR12_POSITIVE_CURRENT_EXPOSURE() {
        return R12_POSITIVE_CURRENT_EXPOSURE;
    }

    public void setR12_POSITIVE_CURRENT_EXPOSURE(BigDecimal r12_POSITIVE_CURRENT_EXPOSURE) {
        R12_POSITIVE_CURRENT_EXPOSURE = r12_POSITIVE_CURRENT_EXPOSURE;
    }

    public BigDecimal getR12_RISK_MULTIPLIER() {
        return R12_RISK_MULTIPLIER;
    }

    public void setR12_RISK_MULTIPLIER(BigDecimal r12_RISK_MULTIPLIER) {
        R12_RISK_MULTIPLIER = r12_RISK_MULTIPLIER;
    }

    public BigDecimal getR12_RWA() {
        return R12_RWA;
    }

    public void setR12_RWA(BigDecimal r12_RWA) {
        R12_RWA = r12_RWA;
    }

    public String getR13_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE() {
        return R13_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public void setR13_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE(
            String r13_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE) {
        R13_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r13_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public BigDecimal getR13_NUMBER_OF_FAILED_TRADES() {
        return R13_NUMBER_OF_FAILED_TRADES;
    }

    public void setR13_NUMBER_OF_FAILED_TRADES(BigDecimal r13_NUMBER_OF_FAILED_TRADES) {
        R13_NUMBER_OF_FAILED_TRADES = r13_NUMBER_OF_FAILED_TRADES;
    }

    public BigDecimal getR13_POSITIVE_CURRENT_EXPOSURE() {
        return R13_POSITIVE_CURRENT_EXPOSURE;
    }

    public void setR13_POSITIVE_CURRENT_EXPOSURE(BigDecimal r13_POSITIVE_CURRENT_EXPOSURE) {
        R13_POSITIVE_CURRENT_EXPOSURE = r13_POSITIVE_CURRENT_EXPOSURE;
    }

    public BigDecimal getR13_RISK_MULTIPLIER() {
        return R13_RISK_MULTIPLIER;
    }

    public void setR13_RISK_MULTIPLIER(BigDecimal r13_RISK_MULTIPLIER) {
        R13_RISK_MULTIPLIER = r13_RISK_MULTIPLIER;
    }

    public BigDecimal getR13_RWA() {
        return R13_RWA;
    }

    public void setR13_RWA(BigDecimal r13_RWA) {
        R13_RWA = r13_RWA;
    }

    public String getR14_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE() {
        return R14_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public void setR14_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE(
            String r14_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE) {
        R14_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r14_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public BigDecimal getR14_NUMBER_OF_FAILED_TRADES() {
        return R14_NUMBER_OF_FAILED_TRADES;
    }

    public void setR14_NUMBER_OF_FAILED_TRADES(BigDecimal r14_NUMBER_OF_FAILED_TRADES) {
        R14_NUMBER_OF_FAILED_TRADES = r14_NUMBER_OF_FAILED_TRADES;
    }

    public BigDecimal getR14_POSITIVE_CURRENT_EXPOSURE() {
        return R14_POSITIVE_CURRENT_EXPOSURE;
    }

    public void setR14_POSITIVE_CURRENT_EXPOSURE(BigDecimal r14_POSITIVE_CURRENT_EXPOSURE) {
        R14_POSITIVE_CURRENT_EXPOSURE = r14_POSITIVE_CURRENT_EXPOSURE;
    }

    public BigDecimal getR14_RISK_MULTIPLIER() {
        return R14_RISK_MULTIPLIER;
    }

    public void setR14_RISK_MULTIPLIER(BigDecimal r14_RISK_MULTIPLIER) {
        R14_RISK_MULTIPLIER = r14_RISK_MULTIPLIER;
    }

    public BigDecimal getR14_RWA() {
        return R14_RWA;
    }

    public void setR14_RWA(BigDecimal r14_RWA) {
        R14_RWA = r14_RWA;
    }

    public String getR15_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE() {
        return R15_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public void setR15_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE(
            String r15_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE) {
        R15_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r15_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public BigDecimal getR15_NUMBER_OF_FAILED_TRADES() {
        return R15_NUMBER_OF_FAILED_TRADES;
    }

    public void setR15_NUMBER_OF_FAILED_TRADES(BigDecimal r15_NUMBER_OF_FAILED_TRADES) {
        R15_NUMBER_OF_FAILED_TRADES = r15_NUMBER_OF_FAILED_TRADES;
    }

    public BigDecimal getR15_POSITIVE_CURRENT_EXPOSURE() {
        return R15_POSITIVE_CURRENT_EXPOSURE;
    }

    public void setR15_POSITIVE_CURRENT_EXPOSURE(BigDecimal r15_POSITIVE_CURRENT_EXPOSURE) {
        R15_POSITIVE_CURRENT_EXPOSURE = r15_POSITIVE_CURRENT_EXPOSURE;
    }

    public BigDecimal getR15_RISK_MULTIPLIER() {
        return R15_RISK_MULTIPLIER;
    }

    public void setR15_RISK_MULTIPLIER(BigDecimal r15_RISK_MULTIPLIER) {
        R15_RISK_MULTIPLIER = r15_RISK_MULTIPLIER;
    }

    public BigDecimal getR15_RWA() {
        return R15_RWA;
    }

    public void setR15_RWA(BigDecimal r15_RWA) {
        R15_RWA = r15_RWA;
    }

    public String getR16_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE() {
        return R16_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public void setR16_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE(
            String r16_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE) {
        R16_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r16_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public BigDecimal getR16_NUMBER_OF_FAILED_TRADES() {
        return R16_NUMBER_OF_FAILED_TRADES;
    }

    public void setR16_NUMBER_OF_FAILED_TRADES(BigDecimal r16_NUMBER_OF_FAILED_TRADES) {
        R16_NUMBER_OF_FAILED_TRADES = r16_NUMBER_OF_FAILED_TRADES;
    }

    public BigDecimal getR16_POSITIVE_CURRENT_EXPOSURE() {
        return R16_POSITIVE_CURRENT_EXPOSURE;
    }

    public void setR16_POSITIVE_CURRENT_EXPOSURE(BigDecimal r16_POSITIVE_CURRENT_EXPOSURE) {
        R16_POSITIVE_CURRENT_EXPOSURE = r16_POSITIVE_CURRENT_EXPOSURE;
    }

    public BigDecimal getR16_RWA() {
        return R16_RWA;
    }

    public void setR16_RWA(BigDecimal r16_RWA) {
        R16_RWA = r16_RWA;
    }

    public String getR19_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE() {
        return R19_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public void setR19_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE(
            String r19_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE) {
        R19_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r19_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public String getR20_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE() {
        return R20_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public void setR20_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE(
            String r20_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE) {
        R20_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r20_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public BigDecimal getR20_NUMBER_OF_FAILED_TRADES() {
        return R20_NUMBER_OF_FAILED_TRADES;
    }

    public void setR20_NUMBER_OF_FAILED_TRADES(BigDecimal r20_NUMBER_OF_FAILED_TRADES) {
        R20_NUMBER_OF_FAILED_TRADES = r20_NUMBER_OF_FAILED_TRADES;
    }

    public BigDecimal getR20_POSITIVE_CURRENT_EXPOSURE() {
        return R20_POSITIVE_CURRENT_EXPOSURE;
    }

    public void setR20_POSITIVE_CURRENT_EXPOSURE(BigDecimal r20_POSITIVE_CURRENT_EXPOSURE) {
        R20_POSITIVE_CURRENT_EXPOSURE = r20_POSITIVE_CURRENT_EXPOSURE;
    }

    public BigDecimal getR20_RISK_MULTIPLIER() {
        return R20_RISK_MULTIPLIER;
    }

    public void setR20_RISK_MULTIPLIER(BigDecimal r20_RISK_MULTIPLIER) {
        R20_RISK_MULTIPLIER = r20_RISK_MULTIPLIER;
    }

    public BigDecimal getR20_RWA() {
        return R20_RWA;
    }

    public void setR20_RWA(BigDecimal r20_RWA) {
        R20_RWA = r20_RWA;
    }

    public String getR21_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE() {
        return R21_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public void setR21_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE(
            String r21_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE) {
        R21_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r21_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public BigDecimal getR21_NUMBER_OF_FAILED_TRADES() {
        return R21_NUMBER_OF_FAILED_TRADES;
    }

    public void setR21_NUMBER_OF_FAILED_TRADES(BigDecimal r21_NUMBER_OF_FAILED_TRADES) {
        R21_NUMBER_OF_FAILED_TRADES = r21_NUMBER_OF_FAILED_TRADES;
    }

    public BigDecimal getR21_POSITIVE_CURRENT_EXPOSURE() {
        return R21_POSITIVE_CURRENT_EXPOSURE;
    }

    public void setR21_POSITIVE_CURRENT_EXPOSURE(BigDecimal r21_POSITIVE_CURRENT_EXPOSURE) {
        R21_POSITIVE_CURRENT_EXPOSURE = r21_POSITIVE_CURRENT_EXPOSURE;
    }

    public BigDecimal getR21_RISK_MULTIPLIER() {
        return R21_RISK_MULTIPLIER;
    }

    public void setR21_RISK_MULTIPLIER(BigDecimal r21_RISK_MULTIPLIER) {
        R21_RISK_MULTIPLIER = r21_RISK_MULTIPLIER;
    }

    public BigDecimal getR21_RWA() {
        return R21_RWA;
    }

    public void setR21_RWA(BigDecimal r21_RWA) {
        R21_RWA = r21_RWA;
    }

    public String getR22_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE() {
        return R22_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public void setR22_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE(
            String r22_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE) {
        R22_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r22_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public BigDecimal getR22_NUMBER_OF_FAILED_TRADES() {
        return R22_NUMBER_OF_FAILED_TRADES;
    }

    public void setR22_NUMBER_OF_FAILED_TRADES(BigDecimal r22_NUMBER_OF_FAILED_TRADES) {
        R22_NUMBER_OF_FAILED_TRADES = r22_NUMBER_OF_FAILED_TRADES;
    }

    public BigDecimal getR22_POSITIVE_CURRENT_EXPOSURE() {
        return R22_POSITIVE_CURRENT_EXPOSURE;
    }

    public void setR22_POSITIVE_CURRENT_EXPOSURE(BigDecimal r22_POSITIVE_CURRENT_EXPOSURE) {
        R22_POSITIVE_CURRENT_EXPOSURE = r22_POSITIVE_CURRENT_EXPOSURE;
    }

    public BigDecimal getR22_RISK_MULTIPLIER() {
        return R22_RISK_MULTIPLIER;
    }

    public void setR22_RISK_MULTIPLIER(BigDecimal r22_RISK_MULTIPLIER) {
        R22_RISK_MULTIPLIER = r22_RISK_MULTIPLIER;
    }

    public BigDecimal getR22_RWA() {
        return R22_RWA;
    }

    public void setR22_RWA(BigDecimal r22_RWA) {
        R22_RWA = r22_RWA;
    }

    public String getR23_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE() {
        return R23_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public void setR23_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE(
            String r23_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE) {
        R23_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r23_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public BigDecimal getR23_NUMBER_OF_FAILED_TRADES() {
        return R23_NUMBER_OF_FAILED_TRADES;
    }

    public void setR23_NUMBER_OF_FAILED_TRADES(BigDecimal r23_NUMBER_OF_FAILED_TRADES) {
        R23_NUMBER_OF_FAILED_TRADES = r23_NUMBER_OF_FAILED_TRADES;
    }

    public BigDecimal getR23_POSITIVE_CURRENT_EXPOSURE() {
        return R23_POSITIVE_CURRENT_EXPOSURE;
    }

    public void setR23_POSITIVE_CURRENT_EXPOSURE(BigDecimal r23_POSITIVE_CURRENT_EXPOSURE) {
        R23_POSITIVE_CURRENT_EXPOSURE = r23_POSITIVE_CURRENT_EXPOSURE;
    }

    public BigDecimal getR23_RISK_MULTIPLIER() {
        return R23_RISK_MULTIPLIER;
    }

    public void setR23_RISK_MULTIPLIER(BigDecimal r23_RISK_MULTIPLIER) {
        R23_RISK_MULTIPLIER = r23_RISK_MULTIPLIER;
    }

    public BigDecimal getR23_RWA() {
        return R23_RWA;
    }

    public void setR23_RWA(BigDecimal r23_RWA) {
        R23_RWA = r23_RWA;
    }

    public String getR24_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE() {
        return R24_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public void setR24_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE(
            String r24_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE) {
        R24_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r24_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public BigDecimal getR24_NUMBER_OF_FAILED_TRADES() {
        return R24_NUMBER_OF_FAILED_TRADES;
    }

    public void setR24_NUMBER_OF_FAILED_TRADES(BigDecimal r24_NUMBER_OF_FAILED_TRADES) {
        R24_NUMBER_OF_FAILED_TRADES = r24_NUMBER_OF_FAILED_TRADES;
    }

    public BigDecimal getR24_POSITIVE_CURRENT_EXPOSURE() {
        return R24_POSITIVE_CURRENT_EXPOSURE;
    }

    public void setR24_POSITIVE_CURRENT_EXPOSURE(BigDecimal r24_POSITIVE_CURRENT_EXPOSURE) {
        R24_POSITIVE_CURRENT_EXPOSURE = r24_POSITIVE_CURRENT_EXPOSURE;
    }

    public BigDecimal getR24_RISK_MULTIPLIER() {
        return R24_RISK_MULTIPLIER;
    }

    public void setR24_RISK_MULTIPLIER(BigDecimal r24_RISK_MULTIPLIER) {
        R24_RISK_MULTIPLIER = r24_RISK_MULTIPLIER;
    }

    public BigDecimal getR24_RWA() {
        return R24_RWA;
    }

    public void setR24_RWA(BigDecimal r24_RWA) {
        R24_RWA = r24_RWA;
    }

    public String getR25_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE() {
        return R25_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public void setR25_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE(
            String r25_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE) {
        R25_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r25_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public BigDecimal getR25_NUMBER_OF_FAILED_TRADES() {
        return R25_NUMBER_OF_FAILED_TRADES;
    }

    public void setR25_NUMBER_OF_FAILED_TRADES(BigDecimal r25_NUMBER_OF_FAILED_TRADES) {
        R25_NUMBER_OF_FAILED_TRADES = r25_NUMBER_OF_FAILED_TRADES;
    }

    public BigDecimal getR25_POSITIVE_CURRENT_EXPOSURE() {
        return R25_POSITIVE_CURRENT_EXPOSURE;
    }

    public void setR25_POSITIVE_CURRENT_EXPOSURE(BigDecimal r25_POSITIVE_CURRENT_EXPOSURE) {
        R25_POSITIVE_CURRENT_EXPOSURE = r25_POSITIVE_CURRENT_EXPOSURE;
    }

    public BigDecimal getR25_RISK_MULTIPLIER() {
        return R25_RISK_MULTIPLIER;
    }

    public void setR25_RISK_MULTIPLIER(BigDecimal r25_RISK_MULTIPLIER) {
        R25_RISK_MULTIPLIER = r25_RISK_MULTIPLIER;
    }

    public BigDecimal getR25_RWA() {
        return R25_RWA;
    }

    public void setR25_RWA(BigDecimal r25_RWA) {
        R25_RWA = r25_RWA;
    }

    public String getR26_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE() {
        return R26_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public void setR26_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE(
            String r26_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE) {
        R26_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r26_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public BigDecimal getR26_NUMBER_OF_FAILED_TRADES() {
        return R26_NUMBER_OF_FAILED_TRADES;
    }

    public void setR26_NUMBER_OF_FAILED_TRADES(BigDecimal r26_NUMBER_OF_FAILED_TRADES) {
        R26_NUMBER_OF_FAILED_TRADES = r26_NUMBER_OF_FAILED_TRADES;
    }

    public BigDecimal getR26_POSITIVE_CURRENT_EXPOSURE() {
        return R26_POSITIVE_CURRENT_EXPOSURE;
    }

    public void setR26_POSITIVE_CURRENT_EXPOSURE(BigDecimal r26_POSITIVE_CURRENT_EXPOSURE) {
        R26_POSITIVE_CURRENT_EXPOSURE = r26_POSITIVE_CURRENT_EXPOSURE;
    }

    public BigDecimal getR26_RISK_MULTIPLIER() {
        return R26_RISK_MULTIPLIER;
    }

    public void setR26_RISK_MULTIPLIER(BigDecimal r26_RISK_MULTIPLIER) {
        R26_RISK_MULTIPLIER = r26_RISK_MULTIPLIER;
    }

    public BigDecimal getR26_RWA() {
        return R26_RWA;
    }

    public void setR26_RWA(BigDecimal r26_RWA) {
        R26_RWA = r26_RWA;
    }

    public String getR27_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE() {
        return R27_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public void setR27_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE(
            String r27_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE) {
        R27_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r27_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public BigDecimal getR27_NUMBER_OF_FAILED_TRADES() {
        return R27_NUMBER_OF_FAILED_TRADES;
    }

    public void setR27_NUMBER_OF_FAILED_TRADES(BigDecimal r27_NUMBER_OF_FAILED_TRADES) {
        R27_NUMBER_OF_FAILED_TRADES = r27_NUMBER_OF_FAILED_TRADES;
    }

    public BigDecimal getR27_POSITIVE_CURRENT_EXPOSURE() {
        return R27_POSITIVE_CURRENT_EXPOSURE;
    }

    public void setR27_POSITIVE_CURRENT_EXPOSURE(BigDecimal r27_POSITIVE_CURRENT_EXPOSURE) {
        R27_POSITIVE_CURRENT_EXPOSURE = r27_POSITIVE_CURRENT_EXPOSURE;
    }

    public BigDecimal getR27_RWA() {
        return R27_RWA;
    }

    public void setR27_RWA(BigDecimal r27_RWA) {
        R27_RWA = r27_RWA;
    }

    public String getR28_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE() {
        return R28_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public void setR28_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE(
            String r28_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE) {
        R28_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE = r28_NUMBER_OF_WORKING_DAYS_AFTER_THE_AGREED_SETTLEMENT_DATE;
    }

    public BigDecimal getR28_NUMBER_OF_FAILED_TRADES() {
        return R28_NUMBER_OF_FAILED_TRADES;
    }

    public void setR28_NUMBER_OF_FAILED_TRADES(BigDecimal r28_NUMBER_OF_FAILED_TRADES) {
        R28_NUMBER_OF_FAILED_TRADES = r28_NUMBER_OF_FAILED_TRADES;
    }

    public BigDecimal getR28_POSITIVE_CURRENT_EXPOSURE() {
        return R28_POSITIVE_CURRENT_EXPOSURE;
    }

    public void setR28_POSITIVE_CURRENT_EXPOSURE(BigDecimal r28_POSITIVE_CURRENT_EXPOSURE) {
        R28_POSITIVE_CURRENT_EXPOSURE = r28_POSITIVE_CURRENT_EXPOSURE;
    }

    public BigDecimal getR28_RWA() {
        return R28_RWA;
    }

    public void setR28_RWA(BigDecimal r28_RWA) {
        R28_RWA = r28_RWA;
    }

    public Date getREPORT_DATE() {
        return REPORT_DATE;
    }

    public void setREPORT_DATE(Date rEPORT_DATE) {
        REPORT_DATE = rEPORT_DATE;
    }

    public String getREPORT_VERSION() {
        return REPORT_VERSION;
    }

    public void setREPORT_VERSION(String rEPORT_VERSION) {
        REPORT_VERSION = rEPORT_VERSION;
    }

    public String getREPORT_FREQUENCY() {
        return REPORT_FREQUENCY;
    }

    public void setREPORT_FREQUENCY(String rEPORT_FREQUENCY) {
        REPORT_FREQUENCY = rEPORT_FREQUENCY;
    }

    public String getREPORT_CODE() {
        return REPORT_CODE;
    }

    public void setREPORT_CODE(String rEPORT_CODE) {
        REPORT_CODE = rEPORT_CODE;
    }

    public String getREPORT_DESC() {
        return REPORT_DESC;
    }

    public void setREPORT_DESC(String rEPORT_DESC) {
        REPORT_DESC = rEPORT_DESC;
    }

    public String getENTITY_FLG() {
        return ENTITY_FLG;
    }

    public void setENTITY_FLG(String eNTITY_FLG) {
        ENTITY_FLG = eNTITY_FLG;
    }

    public String getMODIFY_FLG() {
        return MODIFY_FLG;
    }

    public void setMODIFY_FLG(String mODIFY_FLG) {
        MODIFY_FLG = mODIFY_FLG;
    }

    public String getDEL_FLG() {
        return DEL_FLG;
    }

    public void setDEL_FLG(String dEL_FLG) {
        DEL_FLG = dEL_FLG;
    }
   
     public M_SRWA_12C_Archival_Summary_Entity() {
		super();
		// TODO Auto-generated constructor stub
	}
    

  
}