package com.bornfire.brf.entities;


import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

import com.ibm.icu.math.BigDecimal;

@Entity
@Table(name = "BRRS_M_SRWA_12D_SUMMARYTABLE2")


public class M_SRWA_12D_SUMMARY_ENTITY2{
	
	// R12
	private String r12_residual_maturity_interest_contracts;
	private BigDecimal r12_principal_amount_interest_contracts;
	private BigDecimal r12_total_current_replacement_cost_postive_values_interest_contracts;
	private BigDecimal r12_potential_future_credit_exposure_addon_factors_interest_contracts;
	private BigDecimal r12_potential_future_credit_exposure_amount_interest_contracts;
	private BigDecimal r12_credit_equivalent_amount_interest_contracts;
	private BigDecimal r12_applicable_counterparty_risk_weight_interest_contracts;
	private BigDecimal r12_risk_weighted_asset_interest_contracts;

	// R13
	private String r13_residual_maturity_interest_contracts;
	private BigDecimal r13_principal_amount_interest_contracts;
	private BigDecimal r13_total_current_replacement_cost_postive_values_interest_contracts;
	private BigDecimal r13_potential_future_credit_exposure_addon_factors_interest_contracts;
	private BigDecimal r13_potential_future_credit_exposure_amount_interest_contracts;
	private BigDecimal r13_credit_equivalent_amount_interest_contracts;
	private BigDecimal r13_applicable_counterparty_risk_weight_interest_contracts;
	private BigDecimal r13_risk_weighted_asset_interest_contracts;

	// R14
	private String r14_residual_maturity_interest_contracts;
	private BigDecimal r14_principal_amount_interest_contracts;
	private BigDecimal r14_total_current_replacement_cost_postive_values_interest_contracts;
	private BigDecimal r14_potential_future_credit_exposure_addon_factors_interest_contracts;
	private BigDecimal r14_potential_future_credit_exposure_amount_interest_contracts;
	private BigDecimal r14_credit_equivalent_amount_interest_contracts;
	private BigDecimal r14_applicable_counterparty_risk_weight_interest_contracts;
	private BigDecimal r14_risk_weighted_asset_interest_contracts;

	// R15
	private String r15_residual_maturity_interest_contracts;
	private BigDecimal r15_principal_amount_interest_contracts;
	private BigDecimal r15_total_current_replacement_cost_postive_values_interest_contracts;
	private BigDecimal r15_potential_future_credit_exposure_addon_factors_interest_contracts;
	private BigDecimal r15_potential_future_credit_exposure_amount_interest_contracts;
	private BigDecimal r15_credit_equivalent_amount_interest_contracts;
	private BigDecimal r15_applicable_counterparty_risk_weight_interest_contracts;
	private BigDecimal r15_risk_weighted_asset_interest_contracts;

	// R21
	private String r21_residual_maturity_precious_contracts;
	private BigDecimal r21_principal_amount_precious_contracts;
	private BigDecimal r21_total_current_replacement_cost_postive_values_precious_contracts;
	private BigDecimal r21_potential_future_credit_exposure_addon_factors_precious_contracts;
	private BigDecimal r21_potential_future_credit_exposure_amount_precious_contracts;
	private BigDecimal r21_credit_equivalent_amount_precious_contracts;
	private BigDecimal r21_applicable_counterparty_risk_weight_precious_contracts;
	private BigDecimal r21_risk_weighted_asset_precious_contracts;

	// R22
	private String r22_residual_maturity_precious_contracts;
	private BigDecimal r22_principal_amount_precious_contracts;
	private BigDecimal r22_total_current_replacement_cost_postive_values_precious_contracts;
	private BigDecimal r22_potential_future_credit_exposure_addon_factors_precious_contracts;
	private BigDecimal r22_potential_future_credit_exposure_amount_precious_contracts;
	private BigDecimal r22_credit_equivalent_amount_precious_contracts;
	private BigDecimal r22_applicable_counterparty_risk_weight_precious_contracts;
	private BigDecimal r22_risk_weighted_asset_precious_contracts;

	// R23
	private String r23_residual_maturity_precious_contracts;
	private BigDecimal r23_principal_amount_precious_contracts;
	private BigDecimal r23_total_current_replacement_cost_postive_values_precious_contracts;
	private BigDecimal r23_potential_future_credit_exposure_addon_factors_precious_contracts;
	private BigDecimal r23_potential_future_credit_exposure_amount_precious_contracts;
	private BigDecimal r23_credit_equivalent_amount_precious_contracts;
	private BigDecimal r23_applicable_counterparty_risk_weight_precious_contracts;
	private BigDecimal r23_risk_weighted_asset_precious_contracts;

	// R24
	private String r24_residual_maturity_precious_contracts;
	private BigDecimal r24_principal_amount_precious_contracts;
	private BigDecimal r24_total_current_replacement_cost_postive_values_precious_contracts;
	private BigDecimal r24_potential_future_credit_exposure_addon_factors_precious_contracts;
	private BigDecimal r24_potential_future_credit_exposure_amount_precious_contracts;
	private BigDecimal r24_credit_equivalent_amount_precious_contracts;
	private BigDecimal r24_applicable_counterparty_risk_weight_precious_contracts;
	private BigDecimal r24_risk_weighted_asset_precious_contracts;

	// R30
	private String r30_residual_maturity_credit_contracts;
	private BigDecimal r30_principal_amount_credit_contracts;
	private BigDecimal r30_total_current_replacement_cost_postive_values_credit_contracts;
	private BigDecimal r30_potential_future_credit_exposure_addon_factors_credit_contracts;
	private BigDecimal r30_potential_future_credit_exposure_amount_credit_contracts;
	private BigDecimal r30_credit_equivalent_amount_credit_contracts;
	private BigDecimal r30_applicable_counterparty_risk_weight_credit_contracts;
	private BigDecimal r30_risk_weighted_asset_credit_contracts;

	// R31
	private String r31_residual_maturity_credit_contracts;
	private BigDecimal r31_principal_amount_credit_contracts;
	private BigDecimal r31_total_current_replacement_cost_postive_values_credit_contracts;
	private BigDecimal r31_potential_future_credit_exposure_addon_factors_credit_contracts;
	private BigDecimal r31_potential_future_credit_exposure_amount_credit_contracts;
	private BigDecimal r31_credit_equivalent_amount_credit_contracts;
	private BigDecimal r31_applicable_counterparty_risk_weight_credit_contracts;
	private BigDecimal r31_risk_weighted_asset_credit_contracts;

	// R32
	private String r32_residual_maturity_credit_contracts;
	private BigDecimal r32_principal_amount_credit_contracts;
	private BigDecimal r32_total_current_replacement_cost_postive_values_credit_contracts;
	private BigDecimal r32_potential_future_credit_exposure_addon_factors_credit_contracts;
	private BigDecimal r32_potential_future_credit_exposure_amount_credit_contracts;
	private BigDecimal r32_credit_equivalent_amount_credit_contracts;
	private BigDecimal r32_applicable_counterparty_risk_weight_credit_contracts;
	private BigDecimal r32_risk_weighted_asset_credit_contracts;

	// R33
	private String r33_residual_maturity_credit_contracts;
	private BigDecimal r33_principal_amount_credit_contracts;
	private BigDecimal r33_total_current_replacement_cost_postive_values_credit_contracts;
	private BigDecimal r33_potential_future_credit_exposure_addon_factors_credit_contracts;
	private BigDecimal r33_potential_future_credit_exposure_amount_credit_contracts;
	private BigDecimal r33_credit_equivalent_amount_credit_contracts;
	private BigDecimal r33_applicable_counterparty_risk_weight_credit_contracts;
	private BigDecimal r33_risk_weighted_asset_credit_contracts;
	
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Id
	private Date report_date;
	private String report_version;
	private String report_frequency;
	private String report_code;
	private String report_desc;
	private String entity_flg;
	private String modify_flg;
	private String del_flg;
	public String getR12_residual_maturity_interest_contracts() {
		return r12_residual_maturity_interest_contracts;
	}
	public void setR12_residual_maturity_interest_contracts(String r12_residual_maturity_interest_contracts) {
		this.r12_residual_maturity_interest_contracts = r12_residual_maturity_interest_contracts;
	}
	public BigDecimal getR12_principal_amount_interest_contracts() {
		return r12_principal_amount_interest_contracts;
	}
	public void setR12_principal_amount_interest_contracts(BigDecimal r12_principal_amount_interest_contracts) {
		this.r12_principal_amount_interest_contracts = r12_principal_amount_interest_contracts;
	}
	public BigDecimal getR12_total_current_replacement_cost_postive_values_interest_contracts() {
		return r12_total_current_replacement_cost_postive_values_interest_contracts;
	}
	public void setR12_total_current_replacement_cost_postive_values_interest_contracts(
			BigDecimal r12_total_current_replacement_cost_postive_values_interest_contracts) {
		this.r12_total_current_replacement_cost_postive_values_interest_contracts = r12_total_current_replacement_cost_postive_values_interest_contracts;
	}
	public BigDecimal getR12_potential_future_credit_exposure_addon_factors_interest_contracts() {
		return r12_potential_future_credit_exposure_addon_factors_interest_contracts;
	}
	public void setR12_potential_future_credit_exposure_addon_factors_interest_contracts(
			BigDecimal r12_potential_future_credit_exposure_addon_factors_interest_contracts) {
		this.r12_potential_future_credit_exposure_addon_factors_interest_contracts = r12_potential_future_credit_exposure_addon_factors_interest_contracts;
	}
	public BigDecimal getR12_potential_future_credit_exposure_amount_interest_contracts() {
		return r12_potential_future_credit_exposure_amount_interest_contracts;
	}
	public void setR12_potential_future_credit_exposure_amount_interest_contracts(
			BigDecimal r12_potential_future_credit_exposure_amount_interest_contracts) {
		this.r12_potential_future_credit_exposure_amount_interest_contracts = r12_potential_future_credit_exposure_amount_interest_contracts;
	}
	public BigDecimal getR12_credit_equivalent_amount_interest_contracts() {
		return r12_credit_equivalent_amount_interest_contracts;
	}
	public void setR12_credit_equivalent_amount_interest_contracts(
			BigDecimal r12_credit_equivalent_amount_interest_contracts) {
		this.r12_credit_equivalent_amount_interest_contracts = r12_credit_equivalent_amount_interest_contracts;
	}
	public BigDecimal getR12_applicable_counterparty_risk_weight_interest_contracts() {
		return r12_applicable_counterparty_risk_weight_interest_contracts;
	}
	public void setR12_applicable_counterparty_risk_weight_interest_contracts(
			BigDecimal r12_applicable_counterparty_risk_weight_interest_contracts) {
		this.r12_applicable_counterparty_risk_weight_interest_contracts = r12_applicable_counterparty_risk_weight_interest_contracts;
	}
	public BigDecimal getR12_risk_weighted_asset_interest_contracts() {
		return r12_risk_weighted_asset_interest_contracts;
	}
	public void setR12_risk_weighted_asset_interest_contracts(BigDecimal r12_risk_weighted_asset_interest_contracts) {
		this.r12_risk_weighted_asset_interest_contracts = r12_risk_weighted_asset_interest_contracts;
	}
	public String getR13_residual_maturity_interest_contracts() {
		return r13_residual_maturity_interest_contracts;
	}
	public void setR13_residual_maturity_interest_contracts(String r13_residual_maturity_interest_contracts) {
		this.r13_residual_maturity_interest_contracts = r13_residual_maturity_interest_contracts;
	}
	public BigDecimal getR13_principal_amount_interest_contracts() {
		return r13_principal_amount_interest_contracts;
	}
	public void setR13_principal_amount_interest_contracts(BigDecimal r13_principal_amount_interest_contracts) {
		this.r13_principal_amount_interest_contracts = r13_principal_amount_interest_contracts;
	}
	public BigDecimal getR13_total_current_replacement_cost_postive_values_interest_contracts() {
		return r13_total_current_replacement_cost_postive_values_interest_contracts;
	}
	public void setR13_total_current_replacement_cost_postive_values_interest_contracts(
			BigDecimal r13_total_current_replacement_cost_postive_values_interest_contracts) {
		this.r13_total_current_replacement_cost_postive_values_interest_contracts = r13_total_current_replacement_cost_postive_values_interest_contracts;
	}
	public BigDecimal getR13_potential_future_credit_exposure_addon_factors_interest_contracts() {
		return r13_potential_future_credit_exposure_addon_factors_interest_contracts;
	}
	public void setR13_potential_future_credit_exposure_addon_factors_interest_contracts(
			BigDecimal r13_potential_future_credit_exposure_addon_factors_interest_contracts) {
		this.r13_potential_future_credit_exposure_addon_factors_interest_contracts = r13_potential_future_credit_exposure_addon_factors_interest_contracts;
	}
	public BigDecimal getR13_potential_future_credit_exposure_amount_interest_contracts() {
		return r13_potential_future_credit_exposure_amount_interest_contracts;
	}
	public void setR13_potential_future_credit_exposure_amount_interest_contracts(
			BigDecimal r13_potential_future_credit_exposure_amount_interest_contracts) {
		this.r13_potential_future_credit_exposure_amount_interest_contracts = r13_potential_future_credit_exposure_amount_interest_contracts;
	}
	public BigDecimal getR13_credit_equivalent_amount_interest_contracts() {
		return r13_credit_equivalent_amount_interest_contracts;
	}
	public void setR13_credit_equivalent_amount_interest_contracts(
			BigDecimal r13_credit_equivalent_amount_interest_contracts) {
		this.r13_credit_equivalent_amount_interest_contracts = r13_credit_equivalent_amount_interest_contracts;
	}
	public BigDecimal getR13_applicable_counterparty_risk_weight_interest_contracts() {
		return r13_applicable_counterparty_risk_weight_interest_contracts;
	}
	public void setR13_applicable_counterparty_risk_weight_interest_contracts(
			BigDecimal r13_applicable_counterparty_risk_weight_interest_contracts) {
		this.r13_applicable_counterparty_risk_weight_interest_contracts = r13_applicable_counterparty_risk_weight_interest_contracts;
	}
	public BigDecimal getR13_risk_weighted_asset_interest_contracts() {
		return r13_risk_weighted_asset_interest_contracts;
	}
	public void setR13_risk_weighted_asset_interest_contracts(BigDecimal r13_risk_weighted_asset_interest_contracts) {
		this.r13_risk_weighted_asset_interest_contracts = r13_risk_weighted_asset_interest_contracts;
	}
	public String getR14_residual_maturity_interest_contracts() {
		return r14_residual_maturity_interest_contracts;
	}
	public void setR14_residual_maturity_interest_contracts(String r14_residual_maturity_interest_contracts) {
		this.r14_residual_maturity_interest_contracts = r14_residual_maturity_interest_contracts;
	}
	public BigDecimal getR14_principal_amount_interest_contracts() {
		return r14_principal_amount_interest_contracts;
	}
	public void setR14_principal_amount_interest_contracts(BigDecimal r14_principal_amount_interest_contracts) {
		this.r14_principal_amount_interest_contracts = r14_principal_amount_interest_contracts;
	}
	public BigDecimal getR14_total_current_replacement_cost_postive_values_interest_contracts() {
		return r14_total_current_replacement_cost_postive_values_interest_contracts;
	}
	public void setR14_total_current_replacement_cost_postive_values_interest_contracts(
			BigDecimal r14_total_current_replacement_cost_postive_values_interest_contracts) {
		this.r14_total_current_replacement_cost_postive_values_interest_contracts = r14_total_current_replacement_cost_postive_values_interest_contracts;
	}
	public BigDecimal getR14_potential_future_credit_exposure_addon_factors_interest_contracts() {
		return r14_potential_future_credit_exposure_addon_factors_interest_contracts;
	}
	public void setR14_potential_future_credit_exposure_addon_factors_interest_contracts(
			BigDecimal r14_potential_future_credit_exposure_addon_factors_interest_contracts) {
		this.r14_potential_future_credit_exposure_addon_factors_interest_contracts = r14_potential_future_credit_exposure_addon_factors_interest_contracts;
	}
	public BigDecimal getR14_potential_future_credit_exposure_amount_interest_contracts() {
		return r14_potential_future_credit_exposure_amount_interest_contracts;
	}
	public void setR14_potential_future_credit_exposure_amount_interest_contracts(
			BigDecimal r14_potential_future_credit_exposure_amount_interest_contracts) {
		this.r14_potential_future_credit_exposure_amount_interest_contracts = r14_potential_future_credit_exposure_amount_interest_contracts;
	}
	public BigDecimal getR14_credit_equivalent_amount_interest_contracts() {
		return r14_credit_equivalent_amount_interest_contracts;
	}
	public void setR14_credit_equivalent_amount_interest_contracts(
			BigDecimal r14_credit_equivalent_amount_interest_contracts) {
		this.r14_credit_equivalent_amount_interest_contracts = r14_credit_equivalent_amount_interest_contracts;
	}
	public BigDecimal getR14_applicable_counterparty_risk_weight_interest_contracts() {
		return r14_applicable_counterparty_risk_weight_interest_contracts;
	}
	public void setR14_applicable_counterparty_risk_weight_interest_contracts(
			BigDecimal r14_applicable_counterparty_risk_weight_interest_contracts) {
		this.r14_applicable_counterparty_risk_weight_interest_contracts = r14_applicable_counterparty_risk_weight_interest_contracts;
	}
	public BigDecimal getR14_risk_weighted_asset_interest_contracts() {
		return r14_risk_weighted_asset_interest_contracts;
	}
	public void setR14_risk_weighted_asset_interest_contracts(BigDecimal r14_risk_weighted_asset_interest_contracts) {
		this.r14_risk_weighted_asset_interest_contracts = r14_risk_weighted_asset_interest_contracts;
	}
	public String getR15_residual_maturity_interest_contracts() {
		return r15_residual_maturity_interest_contracts;
	}
	public void setR15_residual_maturity_interest_contracts(String r15_residual_maturity_interest_contracts) {
		this.r15_residual_maturity_interest_contracts = r15_residual_maturity_interest_contracts;
	}
	public BigDecimal getR15_principal_amount_interest_contracts() {
		return r15_principal_amount_interest_contracts;
	}
	public void setR15_principal_amount_interest_contracts(BigDecimal r15_principal_amount_interest_contracts) {
		this.r15_principal_amount_interest_contracts = r15_principal_amount_interest_contracts;
	}
	public BigDecimal getR15_total_current_replacement_cost_postive_values_interest_contracts() {
		return r15_total_current_replacement_cost_postive_values_interest_contracts;
	}
	public void setR15_total_current_replacement_cost_postive_values_interest_contracts(
			BigDecimal r15_total_current_replacement_cost_postive_values_interest_contracts) {
		this.r15_total_current_replacement_cost_postive_values_interest_contracts = r15_total_current_replacement_cost_postive_values_interest_contracts;
	}
	public BigDecimal getR15_potential_future_credit_exposure_addon_factors_interest_contracts() {
		return r15_potential_future_credit_exposure_addon_factors_interest_contracts;
	}
	public void setR15_potential_future_credit_exposure_addon_factors_interest_contracts(
			BigDecimal r15_potential_future_credit_exposure_addon_factors_interest_contracts) {
		this.r15_potential_future_credit_exposure_addon_factors_interest_contracts = r15_potential_future_credit_exposure_addon_factors_interest_contracts;
	}
	public BigDecimal getR15_potential_future_credit_exposure_amount_interest_contracts() {
		return r15_potential_future_credit_exposure_amount_interest_contracts;
	}
	public void setR15_potential_future_credit_exposure_amount_interest_contracts(
			BigDecimal r15_potential_future_credit_exposure_amount_interest_contracts) {
		this.r15_potential_future_credit_exposure_amount_interest_contracts = r15_potential_future_credit_exposure_amount_interest_contracts;
	}
	public BigDecimal getR15_credit_equivalent_amount_interest_contracts() {
		return r15_credit_equivalent_amount_interest_contracts;
	}
	public void setR15_credit_equivalent_amount_interest_contracts(
			BigDecimal r15_credit_equivalent_amount_interest_contracts) {
		this.r15_credit_equivalent_amount_interest_contracts = r15_credit_equivalent_amount_interest_contracts;
	}
	public BigDecimal getR15_applicable_counterparty_risk_weight_interest_contracts() {
		return r15_applicable_counterparty_risk_weight_interest_contracts;
	}
	public void setR15_applicable_counterparty_risk_weight_interest_contracts(
			BigDecimal r15_applicable_counterparty_risk_weight_interest_contracts) {
		this.r15_applicable_counterparty_risk_weight_interest_contracts = r15_applicable_counterparty_risk_weight_interest_contracts;
	}
	public BigDecimal getR15_risk_weighted_asset_interest_contracts() {
		return r15_risk_weighted_asset_interest_contracts;
	}
	public void setR15_risk_weighted_asset_interest_contracts(BigDecimal r15_risk_weighted_asset_interest_contracts) {
		this.r15_risk_weighted_asset_interest_contracts = r15_risk_weighted_asset_interest_contracts;
	}
	public String getR21_residual_maturity_precious_contracts() {
		return r21_residual_maturity_precious_contracts;
	}
	public void setR21_residual_maturity_precious_contracts(String r21_residual_maturity_precious_contracts) {
		this.r21_residual_maturity_precious_contracts = r21_residual_maturity_precious_contracts;
	}
	public BigDecimal getR21_principal_amount_precious_contracts() {
		return r21_principal_amount_precious_contracts;
	}
	public void setR21_principal_amount_precious_contracts(BigDecimal r21_principal_amount_precious_contracts) {
		this.r21_principal_amount_precious_contracts = r21_principal_amount_precious_contracts;
	}
	public BigDecimal getR21_total_current_replacement_cost_postive_values_precious_contracts() {
		return r21_total_current_replacement_cost_postive_values_precious_contracts;
	}
	public void setR21_total_current_replacement_cost_postive_values_precious_contracts(
			BigDecimal r21_total_current_replacement_cost_postive_values_precious_contracts) {
		this.r21_total_current_replacement_cost_postive_values_precious_contracts = r21_total_current_replacement_cost_postive_values_precious_contracts;
	}
	public BigDecimal getR21_potential_future_credit_exposure_addon_factors_precious_contracts() {
		return r21_potential_future_credit_exposure_addon_factors_precious_contracts;
	}
	public void setR21_potential_future_credit_exposure_addon_factors_precious_contracts(
			BigDecimal r21_potential_future_credit_exposure_addon_factors_precious_contracts) {
		this.r21_potential_future_credit_exposure_addon_factors_precious_contracts = r21_potential_future_credit_exposure_addon_factors_precious_contracts;
	}
	public BigDecimal getR21_potential_future_credit_exposure_amount_precious_contracts() {
		return r21_potential_future_credit_exposure_amount_precious_contracts;
	}
	public void setR21_potential_future_credit_exposure_amount_precious_contracts(
			BigDecimal r21_potential_future_credit_exposure_amount_precious_contracts) {
		this.r21_potential_future_credit_exposure_amount_precious_contracts = r21_potential_future_credit_exposure_amount_precious_contracts;
	}
	public BigDecimal getR21_credit_equivalent_amount_precious_contracts() {
		return r21_credit_equivalent_amount_precious_contracts;
	}
	public void setR21_credit_equivalent_amount_precious_contracts(
			BigDecimal r21_credit_equivalent_amount_precious_contracts) {
		this.r21_credit_equivalent_amount_precious_contracts = r21_credit_equivalent_amount_precious_contracts;
	}
	public BigDecimal getR21_applicable_counterparty_risk_weight_precious_contracts() {
		return r21_applicable_counterparty_risk_weight_precious_contracts;
	}
	public void setR21_applicable_counterparty_risk_weight_precious_contracts(
			BigDecimal r21_applicable_counterparty_risk_weight_precious_contracts) {
		this.r21_applicable_counterparty_risk_weight_precious_contracts = r21_applicable_counterparty_risk_weight_precious_contracts;
	}
	public BigDecimal getR21_risk_weighted_asset_precious_contracts() {
		return r21_risk_weighted_asset_precious_contracts;
	}
	public void setR21_risk_weighted_asset_precious_contracts(BigDecimal r21_risk_weighted_asset_precious_contracts) {
		this.r21_risk_weighted_asset_precious_contracts = r21_risk_weighted_asset_precious_contracts;
	}
	public String getR22_residual_maturity_precious_contracts() {
		return r22_residual_maturity_precious_contracts;
	}
	public void setR22_residual_maturity_precious_contracts(String r22_residual_maturity_precious_contracts) {
		this.r22_residual_maturity_precious_contracts = r22_residual_maturity_precious_contracts;
	}
	public BigDecimal getR22_principal_amount_precious_contracts() {
		return r22_principal_amount_precious_contracts;
	}
	public void setR22_principal_amount_precious_contracts(BigDecimal r22_principal_amount_precious_contracts) {
		this.r22_principal_amount_precious_contracts = r22_principal_amount_precious_contracts;
	}
	public BigDecimal getR22_total_current_replacement_cost_postive_values_precious_contracts() {
		return r22_total_current_replacement_cost_postive_values_precious_contracts;
	}
	public void setR22_total_current_replacement_cost_postive_values_precious_contracts(
			BigDecimal r22_total_current_replacement_cost_postive_values_precious_contracts) {
		this.r22_total_current_replacement_cost_postive_values_precious_contracts = r22_total_current_replacement_cost_postive_values_precious_contracts;
	}
	public BigDecimal getR22_potential_future_credit_exposure_addon_factors_precious_contracts() {
		return r22_potential_future_credit_exposure_addon_factors_precious_contracts;
	}
	public void setR22_potential_future_credit_exposure_addon_factors_precious_contracts(
			BigDecimal r22_potential_future_credit_exposure_addon_factors_precious_contracts) {
		this.r22_potential_future_credit_exposure_addon_factors_precious_contracts = r22_potential_future_credit_exposure_addon_factors_precious_contracts;
	}
	public BigDecimal getR22_potential_future_credit_exposure_amount_precious_contracts() {
		return r22_potential_future_credit_exposure_amount_precious_contracts;
	}
	public void setR22_potential_future_credit_exposure_amount_precious_contracts(
			BigDecimal r22_potential_future_credit_exposure_amount_precious_contracts) {
		this.r22_potential_future_credit_exposure_amount_precious_contracts = r22_potential_future_credit_exposure_amount_precious_contracts;
	}
	public BigDecimal getR22_credit_equivalent_amount_precious_contracts() {
		return r22_credit_equivalent_amount_precious_contracts;
	}
	public void setR22_credit_equivalent_amount_precious_contracts(
			BigDecimal r22_credit_equivalent_amount_precious_contracts) {
		this.r22_credit_equivalent_amount_precious_contracts = r22_credit_equivalent_amount_precious_contracts;
	}
	public BigDecimal getR22_applicable_counterparty_risk_weight_precious_contracts() {
		return r22_applicable_counterparty_risk_weight_precious_contracts;
	}
	public void setR22_applicable_counterparty_risk_weight_precious_contracts(
			BigDecimal r22_applicable_counterparty_risk_weight_precious_contracts) {
		this.r22_applicable_counterparty_risk_weight_precious_contracts = r22_applicable_counterparty_risk_weight_precious_contracts;
	}
	public BigDecimal getR22_risk_weighted_asset_precious_contracts() {
		return r22_risk_weighted_asset_precious_contracts;
	}
	public void setR22_risk_weighted_asset_precious_contracts(BigDecimal r22_risk_weighted_asset_precious_contracts) {
		this.r22_risk_weighted_asset_precious_contracts = r22_risk_weighted_asset_precious_contracts;
	}
	public String getR23_residual_maturity_precious_contracts() {
		return r23_residual_maturity_precious_contracts;
	}
	public void setR23_residual_maturity_precious_contracts(String r23_residual_maturity_precious_contracts) {
		this.r23_residual_maturity_precious_contracts = r23_residual_maturity_precious_contracts;
	}
	public BigDecimal getR23_principal_amount_precious_contracts() {
		return r23_principal_amount_precious_contracts;
	}
	public void setR23_principal_amount_precious_contracts(BigDecimal r23_principal_amount_precious_contracts) {
		this.r23_principal_amount_precious_contracts = r23_principal_amount_precious_contracts;
	}
	public BigDecimal getR23_total_current_replacement_cost_postive_values_precious_contracts() {
		return r23_total_current_replacement_cost_postive_values_precious_contracts;
	}
	public void setR23_total_current_replacement_cost_postive_values_precious_contracts(
			BigDecimal r23_total_current_replacement_cost_postive_values_precious_contracts) {
		this.r23_total_current_replacement_cost_postive_values_precious_contracts = r23_total_current_replacement_cost_postive_values_precious_contracts;
	}
	public BigDecimal getR23_potential_future_credit_exposure_addon_factors_precious_contracts() {
		return r23_potential_future_credit_exposure_addon_factors_precious_contracts;
	}
	public void setR23_potential_future_credit_exposure_addon_factors_precious_contracts(
			BigDecimal r23_potential_future_credit_exposure_addon_factors_precious_contracts) {
		this.r23_potential_future_credit_exposure_addon_factors_precious_contracts = r23_potential_future_credit_exposure_addon_factors_precious_contracts;
	}
	public BigDecimal getR23_potential_future_credit_exposure_amount_precious_contracts() {
		return r23_potential_future_credit_exposure_amount_precious_contracts;
	}
	public void setR23_potential_future_credit_exposure_amount_precious_contracts(
			BigDecimal r23_potential_future_credit_exposure_amount_precious_contracts) {
		this.r23_potential_future_credit_exposure_amount_precious_contracts = r23_potential_future_credit_exposure_amount_precious_contracts;
	}
	public BigDecimal getR23_credit_equivalent_amount_precious_contracts() {
		return r23_credit_equivalent_amount_precious_contracts;
	}
	public void setR23_credit_equivalent_amount_precious_contracts(
			BigDecimal r23_credit_equivalent_amount_precious_contracts) {
		this.r23_credit_equivalent_amount_precious_contracts = r23_credit_equivalent_amount_precious_contracts;
	}
	public BigDecimal getR23_applicable_counterparty_risk_weight_precious_contracts() {
		return r23_applicable_counterparty_risk_weight_precious_contracts;
	}
	public void setR23_applicable_counterparty_risk_weight_precious_contracts(
			BigDecimal r23_applicable_counterparty_risk_weight_precious_contracts) {
		this.r23_applicable_counterparty_risk_weight_precious_contracts = r23_applicable_counterparty_risk_weight_precious_contracts;
	}
	public BigDecimal getR23_risk_weighted_asset_precious_contracts() {
		return r23_risk_weighted_asset_precious_contracts;
	}
	public void setR23_risk_weighted_asset_precious_contracts(BigDecimal r23_risk_weighted_asset_precious_contracts) {
		this.r23_risk_weighted_asset_precious_contracts = r23_risk_weighted_asset_precious_contracts;
	}
	public String getR24_residual_maturity_precious_contracts() {
		return r24_residual_maturity_precious_contracts;
	}
	public void setR24_residual_maturity_precious_contracts(String r24_residual_maturity_precious_contracts) {
		this.r24_residual_maturity_precious_contracts = r24_residual_maturity_precious_contracts;
	}
	public BigDecimal getR24_principal_amount_precious_contracts() {
		return r24_principal_amount_precious_contracts;
	}
	public void setR24_principal_amount_precious_contracts(BigDecimal r24_principal_amount_precious_contracts) {
		this.r24_principal_amount_precious_contracts = r24_principal_amount_precious_contracts;
	}
	public BigDecimal getR24_total_current_replacement_cost_postive_values_precious_contracts() {
		return r24_total_current_replacement_cost_postive_values_precious_contracts;
	}
	public void setR24_total_current_replacement_cost_postive_values_precious_contracts(
			BigDecimal r24_total_current_replacement_cost_postive_values_precious_contracts) {
		this.r24_total_current_replacement_cost_postive_values_precious_contracts = r24_total_current_replacement_cost_postive_values_precious_contracts;
	}
	public BigDecimal getR24_potential_future_credit_exposure_addon_factors_precious_contracts() {
		return r24_potential_future_credit_exposure_addon_factors_precious_contracts;
	}
	public void setR24_potential_future_credit_exposure_addon_factors_precious_contracts(
			BigDecimal r24_potential_future_credit_exposure_addon_factors_precious_contracts) {
		this.r24_potential_future_credit_exposure_addon_factors_precious_contracts = r24_potential_future_credit_exposure_addon_factors_precious_contracts;
	}
	public BigDecimal getR24_potential_future_credit_exposure_amount_precious_contracts() {
		return r24_potential_future_credit_exposure_amount_precious_contracts;
	}
	public void setR24_potential_future_credit_exposure_amount_precious_contracts(
			BigDecimal r24_potential_future_credit_exposure_amount_precious_contracts) {
		this.r24_potential_future_credit_exposure_amount_precious_contracts = r24_potential_future_credit_exposure_amount_precious_contracts;
	}
	public BigDecimal getR24_credit_equivalent_amount_precious_contracts() {
		return r24_credit_equivalent_amount_precious_contracts;
	}
	public void setR24_credit_equivalent_amount_precious_contracts(
			BigDecimal r24_credit_equivalent_amount_precious_contracts) {
		this.r24_credit_equivalent_amount_precious_contracts = r24_credit_equivalent_amount_precious_contracts;
	}
	public BigDecimal getR24_applicable_counterparty_risk_weight_precious_contracts() {
		return r24_applicable_counterparty_risk_weight_precious_contracts;
	}
	public void setR24_applicable_counterparty_risk_weight_precious_contracts(
			BigDecimal r24_applicable_counterparty_risk_weight_precious_contracts) {
		this.r24_applicable_counterparty_risk_weight_precious_contracts = r24_applicable_counterparty_risk_weight_precious_contracts;
	}
	public BigDecimal getR24_risk_weighted_asset_precious_contracts() {
		return r24_risk_weighted_asset_precious_contracts;
	}
	public void setR24_risk_weighted_asset_precious_contracts(BigDecimal r24_risk_weighted_asset_precious_contracts) {
		this.r24_risk_weighted_asset_precious_contracts = r24_risk_weighted_asset_precious_contracts;
	}
	public String getR30_residual_maturity_credit_contracts() {
		return r30_residual_maturity_credit_contracts;
	}
	public void setR30_residual_maturity_credit_contracts(String r30_residual_maturity_credit_contracts) {
		this.r30_residual_maturity_credit_contracts = r30_residual_maturity_credit_contracts;
	}
	public BigDecimal getR30_principal_amount_credit_contracts() {
		return r30_principal_amount_credit_contracts;
	}
	public void setR30_principal_amount_credit_contracts(BigDecimal r30_principal_amount_credit_contracts) {
		this.r30_principal_amount_credit_contracts = r30_principal_amount_credit_contracts;
	}
	public BigDecimal getR30_total_current_replacement_cost_postive_values_credit_contracts() {
		return r30_total_current_replacement_cost_postive_values_credit_contracts;
	}
	public void setR30_total_current_replacement_cost_postive_values_credit_contracts(
			BigDecimal r30_total_current_replacement_cost_postive_values_credit_contracts) {
		this.r30_total_current_replacement_cost_postive_values_credit_contracts = r30_total_current_replacement_cost_postive_values_credit_contracts;
	}
	public BigDecimal getR30_potential_future_credit_exposure_addon_factors_credit_contracts() {
		return r30_potential_future_credit_exposure_addon_factors_credit_contracts;
	}
	public void setR30_potential_future_credit_exposure_addon_factors_credit_contracts(
			BigDecimal r30_potential_future_credit_exposure_addon_factors_credit_contracts) {
		this.r30_potential_future_credit_exposure_addon_factors_credit_contracts = r30_potential_future_credit_exposure_addon_factors_credit_contracts;
	}
	public BigDecimal getR30_potential_future_credit_exposure_amount_credit_contracts() {
		return r30_potential_future_credit_exposure_amount_credit_contracts;
	}
	public void setR30_potential_future_credit_exposure_amount_credit_contracts(
			BigDecimal r30_potential_future_credit_exposure_amount_credit_contracts) {
		this.r30_potential_future_credit_exposure_amount_credit_contracts = r30_potential_future_credit_exposure_amount_credit_contracts;
	}
	public BigDecimal getR30_credit_equivalent_amount_credit_contracts() {
		return r30_credit_equivalent_amount_credit_contracts;
	}
	public void setR30_credit_equivalent_amount_credit_contracts(BigDecimal r30_credit_equivalent_amount_credit_contracts) {
		this.r30_credit_equivalent_amount_credit_contracts = r30_credit_equivalent_amount_credit_contracts;
	}
	public BigDecimal getR30_applicable_counterparty_risk_weight_credit_contracts() {
		return r30_applicable_counterparty_risk_weight_credit_contracts;
	}
	public void setR30_applicable_counterparty_risk_weight_credit_contracts(
			BigDecimal r30_applicable_counterparty_risk_weight_credit_contracts) {
		this.r30_applicable_counterparty_risk_weight_credit_contracts = r30_applicable_counterparty_risk_weight_credit_contracts;
	}
	public BigDecimal getR30_risk_weighted_asset_credit_contracts() {
		return r30_risk_weighted_asset_credit_contracts;
	}
	public void setR30_risk_weighted_asset_credit_contracts(BigDecimal r30_risk_weighted_asset_credit_contracts) {
		this.r30_risk_weighted_asset_credit_contracts = r30_risk_weighted_asset_credit_contracts;
	}
	public String getR31_residual_maturity_credit_contracts() {
		return r31_residual_maturity_credit_contracts;
	}
	public void setR31_residual_maturity_credit_contracts(String r31_residual_maturity_credit_contracts) {
		this.r31_residual_maturity_credit_contracts = r31_residual_maturity_credit_contracts;
	}
	public BigDecimal getR31_principal_amount_credit_contracts() {
		return r31_principal_amount_credit_contracts;
	}
	public void setR31_principal_amount_credit_contracts(BigDecimal r31_principal_amount_credit_contracts) {
		this.r31_principal_amount_credit_contracts = r31_principal_amount_credit_contracts;
	}
	public BigDecimal getR31_total_current_replacement_cost_postive_values_credit_contracts() {
		return r31_total_current_replacement_cost_postive_values_credit_contracts;
	}
	public void setR31_total_current_replacement_cost_postive_values_credit_contracts(
			BigDecimal r31_total_current_replacement_cost_postive_values_credit_contracts) {
		this.r31_total_current_replacement_cost_postive_values_credit_contracts = r31_total_current_replacement_cost_postive_values_credit_contracts;
	}
	public BigDecimal getR31_potential_future_credit_exposure_addon_factors_credit_contracts() {
		return r31_potential_future_credit_exposure_addon_factors_credit_contracts;
	}
	public void setR31_potential_future_credit_exposure_addon_factors_credit_contracts(
			BigDecimal r31_potential_future_credit_exposure_addon_factors_credit_contracts) {
		this.r31_potential_future_credit_exposure_addon_factors_credit_contracts = r31_potential_future_credit_exposure_addon_factors_credit_contracts;
	}
	public BigDecimal getR31_potential_future_credit_exposure_amount_credit_contracts() {
		return r31_potential_future_credit_exposure_amount_credit_contracts;
	}
	public void setR31_potential_future_credit_exposure_amount_credit_contracts(
			BigDecimal r31_potential_future_credit_exposure_amount_credit_contracts) {
		this.r31_potential_future_credit_exposure_amount_credit_contracts = r31_potential_future_credit_exposure_amount_credit_contracts;
	}
	public BigDecimal getR31_credit_equivalent_amount_credit_contracts() {
		return r31_credit_equivalent_amount_credit_contracts;
	}
	public void setR31_credit_equivalent_amount_credit_contracts(BigDecimal r31_credit_equivalent_amount_credit_contracts) {
		this.r31_credit_equivalent_amount_credit_contracts = r31_credit_equivalent_amount_credit_contracts;
	}
	public BigDecimal getR31_applicable_counterparty_risk_weight_credit_contracts() {
		return r31_applicable_counterparty_risk_weight_credit_contracts;
	}
	public void setR31_applicable_counterparty_risk_weight_credit_contracts(
			BigDecimal r31_applicable_counterparty_risk_weight_credit_contracts) {
		this.r31_applicable_counterparty_risk_weight_credit_contracts = r31_applicable_counterparty_risk_weight_credit_contracts;
	}
	public BigDecimal getR31_risk_weighted_asset_credit_contracts() {
		return r31_risk_weighted_asset_credit_contracts;
	}
	public void setR31_risk_weighted_asset_credit_contracts(BigDecimal r31_risk_weighted_asset_credit_contracts) {
		this.r31_risk_weighted_asset_credit_contracts = r31_risk_weighted_asset_credit_contracts;
	}
	public String getR32_residual_maturity_credit_contracts() {
		return r32_residual_maturity_credit_contracts;
	}
	public void setR32_residual_maturity_credit_contracts(String r32_residual_maturity_credit_contracts) {
		this.r32_residual_maturity_credit_contracts = r32_residual_maturity_credit_contracts;
	}
	public BigDecimal getR32_principal_amount_credit_contracts() {
		return r32_principal_amount_credit_contracts;
	}
	public void setR32_principal_amount_credit_contracts(BigDecimal r32_principal_amount_credit_contracts) {
		this.r32_principal_amount_credit_contracts = r32_principal_amount_credit_contracts;
	}
	public BigDecimal getR32_total_current_replacement_cost_postive_values_credit_contracts() {
		return r32_total_current_replacement_cost_postive_values_credit_contracts;
	}
	public void setR32_total_current_replacement_cost_postive_values_credit_contracts(
			BigDecimal r32_total_current_replacement_cost_postive_values_credit_contracts) {
		this.r32_total_current_replacement_cost_postive_values_credit_contracts = r32_total_current_replacement_cost_postive_values_credit_contracts;
	}
	public BigDecimal getR32_potential_future_credit_exposure_addon_factors_credit_contracts() {
		return r32_potential_future_credit_exposure_addon_factors_credit_contracts;
	}
	public void setR32_potential_future_credit_exposure_addon_factors_credit_contracts(
			BigDecimal r32_potential_future_credit_exposure_addon_factors_credit_contracts) {
		this.r32_potential_future_credit_exposure_addon_factors_credit_contracts = r32_potential_future_credit_exposure_addon_factors_credit_contracts;
	}
	public BigDecimal getR32_potential_future_credit_exposure_amount_credit_contracts() {
		return r32_potential_future_credit_exposure_amount_credit_contracts;
	}
	public void setR32_potential_future_credit_exposure_amount_credit_contracts(
			BigDecimal r32_potential_future_credit_exposure_amount_credit_contracts) {
		this.r32_potential_future_credit_exposure_amount_credit_contracts = r32_potential_future_credit_exposure_amount_credit_contracts;
	}
	public BigDecimal getR32_credit_equivalent_amount_credit_contracts() {
		return r32_credit_equivalent_amount_credit_contracts;
	}
	public void setR32_credit_equivalent_amount_credit_contracts(BigDecimal r32_credit_equivalent_amount_credit_contracts) {
		this.r32_credit_equivalent_amount_credit_contracts = r32_credit_equivalent_amount_credit_contracts;
	}
	public BigDecimal getR32_applicable_counterparty_risk_weight_credit_contracts() {
		return r32_applicable_counterparty_risk_weight_credit_contracts;
	}
	public void setR32_applicable_counterparty_risk_weight_credit_contracts(
			BigDecimal r32_applicable_counterparty_risk_weight_credit_contracts) {
		this.r32_applicable_counterparty_risk_weight_credit_contracts = r32_applicable_counterparty_risk_weight_credit_contracts;
	}
	public BigDecimal getR32_risk_weighted_asset_credit_contracts() {
		return r32_risk_weighted_asset_credit_contracts;
	}
	public void setR32_risk_weighted_asset_credit_contracts(BigDecimal r32_risk_weighted_asset_credit_contracts) {
		this.r32_risk_weighted_asset_credit_contracts = r32_risk_weighted_asset_credit_contracts;
	}
	public String getR33_residual_maturity_credit_contracts() {
		return r33_residual_maturity_credit_contracts;
	}
	public void setR33_residual_maturity_credit_contracts(String r33_residual_maturity_credit_contracts) {
		this.r33_residual_maturity_credit_contracts = r33_residual_maturity_credit_contracts;
	}
	public BigDecimal getR33_principal_amount_credit_contracts() {
		return r33_principal_amount_credit_contracts;
	}
	public void setR33_principal_amount_credit_contracts(BigDecimal r33_principal_amount_credit_contracts) {
		this.r33_principal_amount_credit_contracts = r33_principal_amount_credit_contracts;
	}
	public BigDecimal getR33_total_current_replacement_cost_postive_values_credit_contracts() {
		return r33_total_current_replacement_cost_postive_values_credit_contracts;
	}
	public void setR33_total_current_replacement_cost_postive_values_credit_contracts(
			BigDecimal r33_total_current_replacement_cost_postive_values_credit_contracts) {
		this.r33_total_current_replacement_cost_postive_values_credit_contracts = r33_total_current_replacement_cost_postive_values_credit_contracts;
	}
	public BigDecimal getR33_potential_future_credit_exposure_addon_factors_credit_contracts() {
		return r33_potential_future_credit_exposure_addon_factors_credit_contracts;
	}
	public void setR33_potential_future_credit_exposure_addon_factors_credit_contracts(
			BigDecimal r33_potential_future_credit_exposure_addon_factors_credit_contracts) {
		this.r33_potential_future_credit_exposure_addon_factors_credit_contracts = r33_potential_future_credit_exposure_addon_factors_credit_contracts;
	}
	public BigDecimal getR33_potential_future_credit_exposure_amount_credit_contracts() {
		return r33_potential_future_credit_exposure_amount_credit_contracts;
	}
	public void setR33_potential_future_credit_exposure_amount_credit_contracts(
			BigDecimal r33_potential_future_credit_exposure_amount_credit_contracts) {
		this.r33_potential_future_credit_exposure_amount_credit_contracts = r33_potential_future_credit_exposure_amount_credit_contracts;
	}
	public BigDecimal getR33_credit_equivalent_amount_credit_contracts() {
		return r33_credit_equivalent_amount_credit_contracts;
	}
	public void setR33_credit_equivalent_amount_credit_contracts(BigDecimal r33_credit_equivalent_amount_credit_contracts) {
		this.r33_credit_equivalent_amount_credit_contracts = r33_credit_equivalent_amount_credit_contracts;
	}
	public BigDecimal getR33_applicable_counterparty_risk_weight_credit_contracts() {
		return r33_applicable_counterparty_risk_weight_credit_contracts;
	}
	public void setR33_applicable_counterparty_risk_weight_credit_contracts(
			BigDecimal r33_applicable_counterparty_risk_weight_credit_contracts) {
		this.r33_applicable_counterparty_risk_weight_credit_contracts = r33_applicable_counterparty_risk_weight_credit_contracts;
	}
	public BigDecimal getR33_risk_weighted_asset_credit_contracts() {
		return r33_risk_weighted_asset_credit_contracts;
	}
	public void setR33_risk_weighted_asset_credit_contracts(BigDecimal r33_risk_weighted_asset_credit_contracts) {
		this.r33_risk_weighted_asset_credit_contracts = r33_risk_weighted_asset_credit_contracts;
	}
	public Date getReport_date() {
		return report_date;
	}
	public void setReport_date(Date report_date) {
		this.report_date = report_date;
	}
	public String getReport_version() {
		return report_version;
	}
	public void setReport_version(String report_version) {
		this.report_version = report_version;
	}
	public String getReport_frequency() {
		return report_frequency;
	}
	public void setReport_frequency(String report_frequency) {
		this.report_frequency = report_frequency;
	}
	public String getReport_code() {
		return report_code;
	}
	public void setReport_code(String report_code) {
		this.report_code = report_code;
	}
	public String getReport_desc() {
		return report_desc;
	}
	public void setReport_desc(String report_desc) {
		this.report_desc = report_desc;
	}
	public String getEntity_flg() {
		return entity_flg;
	}
	public void setEntity_flg(String entity_flg) {
		this.entity_flg = entity_flg;
	}
	public String getModify_flg() {
		return modify_flg;
	}
	public void setModify_flg(String modify_flg) {
		this.modify_flg = modify_flg;
	}
	public String getDel_flg() {
		return del_flg;
	}
	public void setDel_flg(String del_flg) {
		this.del_flg = del_flg;
	}
	public M_SRWA_12D_SUMMARY_ENTITY2() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	
}
